//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package net.minecraft.theTitans;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemAppleGold;
import net.minecraft.item.ItemArmor;
import net.minecraft.potion.Potion;
import net.minecraft.theTitans.items.ItemAdamantium;
import net.minecraft.theTitans.items.ItemAdamantiumSword;
import net.minecraft.theTitans.items.ItemAdminiumArmor;
import net.minecraft.theTitans.items.ItemAdminiumAxe;
import net.minecraft.theTitans.items.ItemAdminiumHoe;
import net.minecraft.theTitans.items.ItemAdminiumSword;
import net.minecraft.theTitans.items.ItemAppleDiamond;
import net.minecraft.theTitans.items.ItemChaff;
import net.minecraft.theTitans.items.ItemCustomArmor;
import net.minecraft.theTitans.items.ItemCustomAxe;
import net.minecraft.theTitans.items.ItemCustomPickaxe;
import net.minecraft.theTitans.items.ItemCustomSpade;
import net.minecraft.theTitans.items.ItemCustomSword;
import net.minecraft.theTitans.items.ItemDiamondString;
import net.minecraft.theTitans.items.ItemEggBlazeTitan;
import net.minecraft.theTitans.items.ItemEggCaveSpiderTitan;
import net.minecraft.theTitans.items.ItemEggChargedCreeperTitan;
import net.minecraft.theTitans.items.ItemEggCreeperTitan;
import net.minecraft.theTitans.items.ItemEggEnderColossus;
import net.minecraft.theTitans.items.ItemEggGhastTitan;
import net.minecraft.theTitans.items.ItemEggMagmaCubeTitan;
import net.minecraft.theTitans.items.ItemEggOmegafish;
import net.minecraft.theTitans.items.ItemEggReinforcedIronGolem;
import net.minecraft.theTitans.items.ItemEggSkeletonTitan;
import net.minecraft.theTitans.items.ItemEggSlimeTitan;
import net.minecraft.theTitans.items.ItemEggSnowGolemTitan;
import net.minecraft.theTitans.items.ItemEggSpiderJockeyTitan;
import net.minecraft.theTitans.items.ItemEggSpiderTitan;
import net.minecraft.theTitans.items.ItemEggUltimaIronGolemTitan;
import net.minecraft.theTitans.items.ItemEggWitherJockeyTitan;
import net.minecraft.theTitans.items.ItemEggWitherSkeletonTitan;
import net.minecraft.theTitans.items.ItemEggWitherzilla;
import net.minecraft.theTitans.items.ItemEggZombiePigmanTitan;
import net.minecraft.theTitans.items.ItemEggZombieTitan;
import net.minecraft.theTitans.items.ItemFoodMalgrum;
import net.minecraft.theTitans.items.ItemForTheChallengeGames1;
import net.minecraft.theTitans.items.ItemGoodTurret;
import net.minecraft.theTitans.items.ItemGoodTurretGround;
import net.minecraft.theTitans.items.ItemGoodTurretMortar;
import net.minecraft.theTitans.items.ItemGrowthSerum;
import net.minecraft.theTitans.items.ItemHarcadium;
import net.minecraft.theTitans.items.ItemHarcadiumArmor;
import net.minecraft.theTitans.items.ItemHarcadiumArrow;
import net.minecraft.theTitans.items.ItemHarcadiumAxe;
import net.minecraft.theTitans.items.ItemHarcadiumBow;
import net.minecraft.theTitans.items.ItemHarcadiumHoe;
import net.minecraft.theTitans.items.ItemHarcadiumPickaxe;
import net.minecraft.theTitans.items.ItemHarcadiumSpade;
import net.minecraft.theTitans.items.ItemHarcadiumSword;
import net.minecraft.theTitans.items.ItemMalgrumSeeds;
import net.minecraft.theTitans.items.ItemOptimaAxe;
import net.minecraft.theTitans.items.ItemPleasantBladeBrew;
import net.minecraft.theTitans.items.ItemPleasantBladeFlower;
import net.minecraft.theTitans.items.ItemPleasantBladeSeed;
import net.minecraft.theTitans.items.ItemSpawnEggTitans;
import net.minecraft.theTitans.items.ItemTeleporter;
import net.minecraft.theTitans.items.ItemTeleporter2;
import net.minecraft.theTitans.items.ItemUltimaBlade;
import net.minecraft.theTitans.items.ItemVoid;
import net.minecraft.theTitans.items.ItemVoidArmor;
import net.minecraft.theTitans.items.ItemVoidAxe;
import net.minecraft.theTitans.items.ItemVoidHoe;
import net.minecraft.theTitans.items.ItemVoidPickaxe;
import net.minecraft.theTitans.items.ItemVoidSpade;
import net.minecraft.theTitans.items.ItemVoidSword;
import net.minecraftforge.common.util.EnumHelper;

public class TitanItems {
    public static ItemArmor.ArmorMaterial enumArmorMaterialAdminium = EnumHelper.addArmorMaterial("AdminiumArmor", 100000000, new int[]{100000, 100000, 100000, 100000}, 60);
    public static ItemArmor.ArmorMaterial enumArmorMaterialAbsence = EnumHelper.addArmorMaterial("AbsenceArmor", 100000, new int[]{11, 17, 13, 9}, 50);
    public static ItemArmor.ArmorMaterial enumArmorMaterialHarcadium = EnumHelper.addArmorMaterial("HarcadiumArmor", 10000, new int[]{9, 15, 12, 8}, 30);
    public static ItemArmor.ArmorMaterial enumArmorMaterialSteel = EnumHelper.addArmorMaterial("SteelArmor", 30, new int[]{3, 8, 6, 3}, 20);
    public static ItemArmor.ArmorMaterial enumArmorMaterialBronze = EnumHelper.addArmorMaterial("BronzeArmor", 12, new int[]{2, 6, 4, 2}, 14);
    public static ItemArmor.ArmorMaterial enumArmorMaterialTin = EnumHelper.addArmorMaterial("TinArmor", 6, new int[]{1, 3, 2, 1}, 18);
    public static ItemArmor.ArmorMaterial enumArmorMaterialCopper = EnumHelper.addArmorMaterial("CopperArmor", 6, new int[]{1, 3, 2, 1}, 12);
    public static Item.ToolMaterial GoodTurret = EnumHelper.addToolMaterial("GoodTurret", 0, 80, 0.0F, 26.0F, 50);
    public static Item.ToolMaterial enumToolMaterialAdminium = EnumHelper.addToolMaterial("AdminiumTools", Integer.MAX_VALUE, 1000000000, 1.0E9F, 1.0E9F, 60);
    public static Item.ToolMaterial enumToolMaterialAbsence = EnumHelper.addToolMaterial("AbsenceTools", 100000000, 1000000, 4000.0F, 1496.0F, 40);
    public static Item.ToolMaterial enumToolMaterialHarcadium = EnumHelper.addToolMaterial("HarcadiumTools", 1000, 75000, 120.0F, 46.0F, 30);
    public static Item.ToolMaterial enumToolMaterialSteel = EnumHelper.addToolMaterial("SteelTools", 3, 900, 8.0F, 3.0F, 10);
    public static Item.ToolMaterial enumToolMaterialBronze = EnumHelper.addToolMaterial("BronzeTools", 2, 200, 6.0F, 2.0F, 14);
    public static Item.ToolMaterial enumToolMaterialTin = EnumHelper.addToolMaterial("TinTools", 1, 100, 3.0F, 1.0F, 18);
    public static Item.ToolMaterial enumToolMaterialCopper = EnumHelper.addToolMaterial("CopperTools", 0, 80, 3.0F, 0.0F, 12);
    public static Item harcadium;
    public static Item harcadiumNugget;
    public static Item harcadiumWafer;
    public static Item harcadiumWaflet;
    public static Item harcadiumPickaxe;
    public static Item harcadiumAxe;
    public static Item harcadiumSpade;
    public static Item harcadiumHoe;
    public static Item harcadiumSword;
    public static Item harcadiumHelmet;
    public static Item harcadiumChestplate;
    public static Item harcadiumLeggings;
    public static Item harcadiumBoots;
    public static Item growthSerum;
    public static Item teleporter;
    public static Item teleporter2;
    public static Item goodTurret;
    public static Item goodTurret2;
    public static Item goodTurret3;
    public static Item goldenPotatoe;
    public static Item goldenCookie;
    public static Item goldenBread;
    public static Item goldenMelon;
    public static Item goldenPumpkinPie;
    public static Item diamondApple;
    public static Item diamondPotatoe;
    public static Item diamondCookie;
    public static Item diamondBread;
    public static Item diamondMelon;
    public static Item diamondPumpkinPie;
    public static Item malgrum;
    public static Item malgrumSeeds;
    public static Item pleasantBladeSeed;
    public static Item pleasantBladeLeaf;
    public static Item pleasantBladeFlower;
    public static Item pleasantBladeBrew;
    public static Item chaff;
    public static Item diamondString;
    public static Item harcadiumArrow;
    public static Item harcadiumBow;
    public static Item witherSkeletonSpawner;
    public static Item eggOmegafish;
    public static Item eggCaveSpiderTitan;
    public static Item eggSpiderTitan;
    public static Item eggSpiderJockeyTitan;
    public static Item eggSlimeTitan;
    public static Item eggMagmaCubeTitan;
    public static Item eggZombieTitan;
    public static Item eggSkeletonTitan;
    public static Item eggCreeperTitan;
    public static Item eggChargedCreeperTitan;
    public static Item eggZombiePigmanTitan;
    public static Item eggBlazeTitan;
    public static Item eggWitherSkeletonTitan;
    public static Item eggWitherJockeyTitan;
    public static Item eggGhastTitan;
    public static Item eggEnderColossus;
    public static Item eggWitherzilla;
    public static Item ultimaBlade;
    public static Item optimaAxe;
    public static Item adamantiumSword;
    public static Item eggUltimaIronGolemTitan;
    public static Item eggIronGolemBetter;
    public static Item eggSnowGolemTitan;
    public static Item adminiumHelmet;
    public static Item adminiumChestplate;
    public static Item adminiumLeggings;
    public static Item adminiumBoots;
    public static Item adminiumPickaxe;
    public static Item adminiumAxe;
    public static Item adminiumSpade;
    public static Item adminiumHoe;
    public static Item adminiumSword;
    public static Item voidItem;
    public static Item voidHelmet;
    public static Item voidChestplate;
    public static Item voidLeggings;
    public static Item voidBoots;
    public static Item voidPickaxe;
    public static Item voidAxe;
    public static Item voidSpade;
    public static Item voidHoe;
    public static Item voidSword;
    public static Item copperIngot;
    public static Item copperPickaxe;
    public static Item copperAxe;
    public static Item copperSpade;
    public static Item copperHoe;
    public static Item copperSword;
    public static Item copperHelmet;
    public static Item copperChestplate;
    public static Item copperLeggings;
    public static Item copperBoots;
    public static Item tinIngot;
    public static Item tinPickaxe;
    public static Item tinAxe;
    public static Item tinSpade;
    public static Item tinHoe;
    public static Item tinSword;
    public static Item tinHelmet;
    public static Item tinChestplate;
    public static Item tinLeggings;
    public static Item tinBoots;
    public static Item bronzeIngot;
    public static Item bronzePickaxe;
    public static Item bronzeAxe;
    public static Item bronzeSpade;
    public static Item bronzeHoe;
    public static Item bronzeSword;
    public static Item bronzeHelmet;
    public static Item bronzeChestplate;
    public static Item bronzeLeggings;
    public static Item bronzeBoots;
    public static Item steelIngot;
    public static Item steelPickaxe;
    public static Item steelAxe;
    public static Item steelSpade;
    public static Item steelHoe;
    public static Item steelSword;
    public static Item steelHelmet;
    public static Item steelChestplate;
    public static Item steelLeggings;
    public static Item steelBoots;
    public static Item chromiumIngot;
    public static Item magnesiumIngot;
    public static Item leadIngot;
    public static Item silverIngot;
    public static Item platinumIngot;
    public static Item ruby;
    public static Item onyx;
    public static Item adamantium;
    public static Item OverlordScorpionEgg;
    public static Item MethuselahKrakenEgg;

    public TitanItems() {
    }

    public static void init() {
        ultimaBlade = new ItemUltimaBlade("ultima_blade");
        optimaAxe = new ItemOptimaAxe("optima_axe");
        adamantiumSword = new ItemAdamantiumSword("adamantium_sword");
        harcadiumWaflet = new ItemHarcadium("harcadium_waflet");
        harcadiumWafer = new ItemHarcadium("harcadium_wafer");
        harcadiumNugget = new ItemHarcadium("harcadium_nugget");
        harcadium = new ItemHarcadium("harcadium");
        voidItem = new ItemVoid("void");
        adamantium = new ItemAdamantium("adamantium");
        copperIngot = (new Item()).func_77655_b("copper_ingot").func_111206_d("thetitans:copper_ingot").func_77637_a(TheTitans.titansTab);
        copperPickaxe = new ItemCustomPickaxe("copper_pickaxe", enumToolMaterialCopper);
        copperAxe = new ItemCustomAxe("copper_axe", enumToolMaterialCopper);
        copperSpade = new ItemCustomSpade("copper_spade", enumToolMaterialCopper);
        copperHoe = new ItemCustomHoe("copper_hoe", enumToolMaterialCopper);
        copperSword = new ItemCustomSword("copper_sword", enumToolMaterialCopper);
        copperHelmet = new ItemCustomArmor("copper_helmet", enumArmorMaterialCopper, 0, "copper_layer_");
        copperChestplate = new ItemCustomArmor("copper_chestplate", enumArmorMaterialCopper, 1, "copper_layer_");
        copperLeggings = new ItemCustomArmor("copper_leggings", enumArmorMaterialCopper, 2, "copper_layer_");
        copperBoots = new ItemCustomArmor("copper_boots", enumArmorMaterialCopper, 3, "copper_layer_");
        tinIngot = (new Item()).func_77655_b("tin_ingot").func_111206_d("thetitans:tin_ingot").func_77637_a(TheTitans.titansTab);
        tinPickaxe = new ItemCustomPickaxe("tin_pickaxe", enumToolMaterialTin);
        tinAxe = new ItemCustomAxe("tin_axe", enumToolMaterialTin);
        tinSpade = new ItemCustomSpade("tin_spade", enumToolMaterialTin);
        tinHoe = new ItemCustomHoe("tin_hoe", enumToolMaterialTin);
        tinSword = new ItemCustomSword("tin_sword", enumToolMaterialTin);
        tinHelmet = new ItemCustomArmor("tin_helmet", enumArmorMaterialTin, 0, "tin_layer_");
        tinChestplate = new ItemCustomArmor("tin_chestplate", enumArmorMaterialTin, 1, "tin_layer_");
        tinLeggings = new ItemCustomArmor("tin_leggings", enumArmorMaterialTin, 2, "tin_layer_");
        tinBoots = new ItemCustomArmor("tin_boots", enumArmorMaterialTin, 3, "tin_layer_");
        bronzeIngot = (new Item()).func_77655_b("bronze_ingot").func_111206_d("thetitans:bronze_ingot").func_77637_a(TheTitans.titansTab);
        bronzePickaxe = new ItemCustomPickaxe("bronze_pickaxe", enumToolMaterialBronze);
        bronzeAxe = new ItemCustomAxe("bronze_axe", enumToolMaterialBronze);
        bronzeSpade = new ItemCustomSpade("bronze_spade", enumToolMaterialBronze);
        bronzeHoe = new ItemCustomHoe("bronze_hoe", enumToolMaterialBronze);
        bronzeSword = new ItemCustomSword("bronze_sword", enumToolMaterialBronze);
        bronzeHelmet = new ItemCustomArmor("bronze_helmet", enumArmorMaterialBronze, 0, "bronze_layer_");
        bronzeChestplate = new ItemCustomArmor("bronze_chestplate", enumArmorMaterialBronze, 1, "bronze_layer_");
        bronzeLeggings = new ItemCustomArmor("bronze_leggings", enumArmorMaterialBronze, 2, "bronze_layer_");
        bronzeBoots = new ItemCustomArmor("bronze_boots", enumArmorMaterialBronze, 3, "bronze_layer_");
        steelIngot = (new Item()).func_77655_b("steel_ingot").func_111206_d("thetitans:steel_ingot").func_77637_a(TheTitans.titansTab);
        steelPickaxe = new ItemCustomPickaxe("steel_pickaxe", enumToolMaterialSteel);
        steelAxe = new ItemCustomAxe("steel_axe", enumToolMaterialSteel);
        steelSpade = new ItemCustomSpade("steel_spade", enumToolMaterialSteel);
        steelHoe = new ItemCustomHoe("steel_hoe", enumToolMaterialSteel);
        steelSword = new ItemCustomSword("steel_sword", enumToolMaterialSteel);
        steelHelmet = new ItemCustomArmor("steel_helmet", enumArmorMaterialSteel, 0, "steel_layer_");
        steelChestplate = new ItemCustomArmor("steel_chestplate", enumArmorMaterialSteel, 1, "steel_layer_");
        steelLeggings = new ItemCustomArmor("steel_leggings", enumArmorMaterialSteel, 2, "steel_layer_");
        steelBoots = new ItemCustomArmor("steel_boots", enumArmorMaterialSteel, 3, "steel_layer_");
        chromiumIngot = (new Item()).func_77655_b("chromium_ingot").func_111206_d("thetitans:chromium_ingot").func_77637_a(TheTitans.titansTab);
        magnesiumIngot = (new Item()).func_77655_b("magnesium_ingot").func_111206_d("thetitans:magnesium_ingot").func_77637_a(TheTitans.titansTab);
        leadIngot = (new Item()).func_77655_b("lead_ingot").func_111206_d("thetitans:lead_ingot").func_77637_a(TheTitans.titansTab);
        silverIngot = (new Item()).func_77655_b("silver_ingot").func_111206_d("thetitans:silver_ingot").func_77637_a(TheTitans.titansTab);
        platinumIngot = (new Item()).func_77655_b("platinum_ingot").func_111206_d("thetitans:platinum_ingot").func_77637_a(TheTitans.titansTab);
        harcadiumBow = new ItemHarcadiumBow();
        harcadiumPickaxe = new ItemHarcadiumPickaxe("harcadium_pickaxe", enumToolMaterialHarcadium);
        harcadiumAxe = new ItemHarcadiumAxe("harcadium_axe", enumToolMaterialHarcadium);
        harcadiumSpade = new ItemHarcadiumSpade("harcadium_spade", enumToolMaterialHarcadium);
        harcadiumHoe = new ItemHarcadiumHoe("harcadium_hoe", enumToolMaterialHarcadium);
        harcadiumSword = new ItemHarcadiumSword("harcadium_sword", enumToolMaterialHarcadium);
        harcadiumHelmet = new ItemHarcadiumArmor("harcadium_helmet", enumArmorMaterialHarcadium, 0);
        harcadiumChestplate = new ItemHarcadiumArmor("harcadium_chestplate", enumArmorMaterialHarcadium, 1);
        harcadiumLeggings = new ItemHarcadiumArmor("harcadium_leggings", enumArmorMaterialHarcadium, 2);
        harcadiumBoots = new ItemHarcadiumArmor("harcadium_boots", enumArmorMaterialHarcadium, 3);
        growthSerum = new ItemGrowthSerum("growth_serum");
        teleporter = new ItemTeleporter("teleporter");
        teleporter2 = new ItemTeleporter2("teleporter2");
        goodTurret = new ItemGoodTurret("turret_good", GoodTurret);
        goodTurret2 = new ItemGoodTurretGround("machine_gun_good", GoodTurret);
        goodTurret3 = new ItemGoodTurretMortar("mortar_good", GoodTurret);
        goldenPotatoe = (new ItemAppleGold(6, 1.2F, false)).func_77848_i().func_77844_a(Potion.field_76428_l.field_76415_H, 5, 1, 1.0F).func_77655_b("golden_potatoe").func_111206_d("thetitans:golden_potatoe").func_77637_a(TheTitans.titansTab);
        goldenBread = (new ItemAppleGold(5, 1.2F, false)).func_77848_i().func_77844_a(Potion.field_76428_l.field_76415_H, 5, 1, 1.0F).func_77655_b("golden_bread").func_111206_d("thetitans:golden_bread").func_77637_a(TheTitans.titansTab);
        goldenCookie = (new ItemAppleGold(2, 1.2F, false)).func_77848_i().func_77844_a(Potion.field_76428_l.field_76415_H, 5, 1, 1.0F).func_77655_b("golden_cookie").func_111206_d("thetitans:golden_cookie").func_77637_a(TheTitans.titansTab);
        goldenMelon = (new ItemAppleGold(2, 1.2F, false)).func_77848_i().func_77844_a(Potion.field_76428_l.field_76415_H, 5, 1, 1.0F).func_77655_b("golden_melon").func_111206_d("thetitans:golden_melon").func_77637_a(TheTitans.titansTab);
        goldenPumpkinPie = (new ItemAppleGold(8, 1.2F, false)).func_77848_i().func_77844_a(Potion.field_76428_l.field_76415_H, 5, 1, 1.0F).func_77655_b("golden_pumpkin_pie").func_111206_d("thetitans:golden_pumpkin_pie").func_77637_a(TheTitans.titansTab);
        diamondApple = (new ItemAppleDiamond(4, 2.4F, false)).func_77848_i().func_77655_b("apple_diamond").func_111206_d("thetitans:apple_diamond").func_77637_a(CreativeTabs.field_78039_h);
        diamondPotatoe = (new ItemAppleDiamond(6, 2.4F, false)).func_77848_i().func_77655_b("diamond_potatoe").func_111206_d("thetitans:diamond_potatoe").func_77637_a(TheTitans.titansTab);
        diamondBread = (new ItemAppleDiamond(5, 2.4F, false)).func_77848_i().func_77655_b("diamond_bread").func_111206_d("thetitans:diamond_bread").func_77637_a(TheTitans.titansTab);
        diamondCookie = (new ItemAppleDiamond(2, 2.4F, false)).func_77848_i().func_77655_b("diamond_cookie").func_111206_d("thetitans:diamond_cookie").func_77637_a(TheTitans.titansTab);
        diamondMelon = (new ItemAppleDiamond(2, 2.4F, false)).func_77848_i().func_77655_b("diamond_melon").func_111206_d("thetitans:diamond_melon").func_77637_a(TheTitans.titansTab);
        diamondPumpkinPie = (new ItemAppleDiamond(8, 2.4F, false)).func_77848_i().func_77655_b("diamond_pumpkin_pie").func_111206_d("thetitans:diamond_pumpkin_pie").func_77637_a(TheTitans.titansTab);
        malgrum = (new ItemFoodMalgrum(20, 20.0F, false)).func_77848_i().func_77655_b("malgrum_fruit").func_111206_d("thetitans:malgrum_fruit").func_77637_a(TheTitans.titansTab);
        malgrumSeeds = new ItemMalgrumSeeds();
        pleasantBladeBrew = new ItemPleasantBladeBrew();
        pleasantBladeFlower = (new ItemPleasantBladeFlower(2, 1.2F, false)).func_77655_b("pleasant_blade_flower").func_111206_d("thetitans:pleasant_blade_flower").func_77637_a(TheTitans.titansTab);
        pleasantBladeLeaf = (new Item()).func_77655_b("pleasant_blade_leaf").func_111206_d("thetitans:pleasant_blade_leaf").func_77637_a(TheTitans.titansTab);
        pleasantBladeSeed = new ItemPleasantBladeSeed();
        chaff = new ItemChaff("chaff");
        diamondString = new ItemDiamondString("diamond_string");
        harcadiumArrow = new ItemHarcadiumArrow("harcadium_arrow");
        witherSkeletonSpawner = new ItemForTheChallengeGames1("witherskeletonspawn");
        eggIronGolemBetter = new ItemEggReinforcedIronGolem("spawn_egg_iron_golem_better");
        eggSnowGolemTitan = new ItemEggSnowGolemTitan("spawn_egg_snow_golem_titan");
        eggSlimeTitan = new ItemEggSlimeTitan("spawn_egg_slime_titan");
        eggMagmaCubeTitan = new ItemEggMagmaCubeTitan("spawn_egg_magma_cube_titan");
        eggOmegafish = new ItemEggOmegafish("spawn_egg_omegafish");
        eggCaveSpiderTitan = new ItemEggCaveSpiderTitan("spawn_egg_cave_spider_titan");
        eggSpiderTitan = new ItemEggSpiderTitan("spawn_egg_spider_titan");
        eggSpiderJockeyTitan = new ItemEggSpiderJockeyTitan("spawn_egg_spider_jockey_titan");
        eggZombieTitan = new ItemEggZombieTitan("spawn_egg_zombie_titan");
        eggSkeletonTitan = new ItemEggSkeletonTitan("spawn_egg_skeleton_titan");
        eggCreeperTitan = new ItemEggCreeperTitan("spawn_egg_creeper_titan");
        eggChargedCreeperTitan = new ItemEggChargedCreeperTitan("spawn_egg_charged_creeper_titan");
        eggZombiePigmanTitan = new ItemEggZombiePigmanTitan("spawn_egg_zombie_pigman_titan");
        eggBlazeTitan = new ItemEggBlazeTitan("spawn_egg_blaze_titan");
        eggWitherSkeletonTitan = new ItemEggWitherSkeletonTitan("spawn_egg_wither_skeleton_titan");
        eggWitherJockeyTitan = new ItemEggWitherJockeyTitan("spawn_egg_wither_jockey_titan");
        eggEnderColossus = new ItemEggEnderColossus("spawn_egg_ender_colossus");
        eggGhastTitan = new ItemEggGhastTitan("spawn_egg_ghast_titan");
        eggUltimaIronGolemTitan = new ItemEggUltimaIronGolemTitan("spawn_egg_iron_golem_titan");
        eggWitherzilla = new ItemEggWitherzilla("spawn_egg_witherzilla");
        adminiumHelmet = new ItemAdminiumArmor("adminium_helmet", enumArmorMaterialAdminium, 0);
        adminiumChestplate = new ItemAdminiumArmor("adminium_chestplate", enumArmorMaterialAdminium, 1);
        adminiumLeggings = new ItemAdminiumArmor("adminium_leggings", enumArmorMaterialAdminium, 2);
        adminiumBoots = new ItemAdminiumArmor("adminium_boots", enumArmorMaterialAdminium, 3);
        adminiumPickaxe = new ItemAdminiumPickaxe("adminium_pickaxe", enumToolMaterialAdminium);
        adminiumAxe = new ItemAdminiumAxe("adminium_axe", enumToolMaterialAdminium);
        adminiumSpade = new ItemAdminiumSpade("adminium_spade", enumToolMaterialAdminium);
        adminiumHoe = new ItemAdminiumHoe("adminium_hoe", enumToolMaterialAdminium);
        adminiumSword = new ItemAdminiumSword("adminium_sword", enumToolMaterialAdminium);
        voidPickaxe = new ItemVoidPickaxe("void_pickaxe", enumToolMaterialAbsence);
        voidAxe = new ItemVoidAxe("void_axe", enumToolMaterialAbsence);
        voidSpade = new ItemVoidSpade("void_spade", enumToolMaterialAbsence);
        voidHoe = new ItemVoidHoe("void_hoe", enumToolMaterialAbsence);
        voidSword = new ItemVoidSword("void_sword", enumToolMaterialAbsence);
        voidHelmet = new ItemVoidArmor("void_helmet", enumArmorMaterialAbsence, 0);
        voidChestplate = new ItemVoidArmor("void_chestplate", enumArmorMaterialAbsence, 1);
        voidLeggings = new ItemVoidArmor("void_leggings", enumArmorMaterialAbsence, 2);
        voidBoots = new ItemVoidArmor("void_boots", enumArmorMaterialAbsence, 3);
        GameRegistry.registerItem(ultimaBlade, ultimaBlade.func_77658_a().substring(5));
        GameRegistry.registerItem(optimaAxe, optimaAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(adamantium, adamantium.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumHelmet, adminiumHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumChestplate, adminiumChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumLeggings, adminiumLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumBoots, adminiumBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumSword, adminiumSword.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumAxe, adminiumAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumPickaxe, adminiumPickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumSpade, adminiumSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(adminiumHoe, adminiumHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(voidItem, voidItem.func_77658_a().substring(5));
        GameRegistry.registerItem(voidHelmet, voidHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(voidChestplate, voidChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(voidLeggings, voidLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(voidBoots, voidBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(voidSword, voidSword.func_77658_a().substring(5));
        GameRegistry.registerItem(voidAxe, voidAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(voidPickaxe, voidPickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(voidSpade, voidSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(voidHoe, voidHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondString, diamondString.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumWaflet, harcadiumWaflet.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumWafer, harcadiumWafer.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumNugget, harcadiumNugget.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadium, harcadium.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumBow, harcadiumBow.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumArrow, harcadiumArrow.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumHelmet, harcadiumHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumChestplate, harcadiumChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumLeggings, harcadiumLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumBoots, harcadiumBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumSword, harcadiumSword.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumAxe, harcadiumAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumPickaxe, harcadiumPickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumSpade, harcadiumSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(harcadiumHoe, harcadiumHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(copperIngot, copperIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(copperHelmet, copperHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(copperChestplate, copperChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(copperLeggings, copperLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(copperBoots, copperBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(copperSword, copperSword.func_77658_a().substring(5));
        GameRegistry.registerItem(copperAxe, copperAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(copperPickaxe, copperPickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(copperSpade, copperSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(copperHoe, copperHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(tinIngot, tinIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(tinHelmet, tinHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(tinChestplate, tinChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(tinLeggings, tinLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(tinBoots, tinBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(tinSword, tinSword.func_77658_a().substring(5));
        GameRegistry.registerItem(tinAxe, tinAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(tinPickaxe, tinPickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(tinSpade, tinSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(tinHoe, tinHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeIngot, bronzeIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeHelmet, bronzeHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeChestplate, bronzeChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeLeggings, bronzeLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeBoots, bronzeBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeSword, bronzeSword.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeAxe, bronzeAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzePickaxe, bronzePickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeSpade, bronzeSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(bronzeHoe, bronzeHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(steelIngot, steelIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(steelHelmet, steelHelmet.func_77658_a().substring(5));
        GameRegistry.registerItem(steelChestplate, steelChestplate.func_77658_a().substring(5));
        GameRegistry.registerItem(steelLeggings, steelLeggings.func_77658_a().substring(5));
        GameRegistry.registerItem(steelBoots, steelBoots.func_77658_a().substring(5));
        GameRegistry.registerItem(steelSword, steelSword.func_77658_a().substring(5));
        GameRegistry.registerItem(steelAxe, steelAxe.func_77658_a().substring(5));
        GameRegistry.registerItem(steelPickaxe, steelPickaxe.func_77658_a().substring(5));
        GameRegistry.registerItem(steelSpade, steelSpade.func_77658_a().substring(5));
        GameRegistry.registerItem(steelHoe, steelHoe.func_77658_a().substring(5));
        GameRegistry.registerItem(chromiumIngot, chromiumIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(magnesiumIngot, magnesiumIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(leadIngot, leadIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(silverIngot, silverIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(platinumIngot, platinumIngot.func_77658_a().substring(5));
        GameRegistry.registerItem(growthSerum, growthSerum.func_77658_a().substring(5));
        GameRegistry.registerItem(teleporter, teleporter.func_77658_a().substring(5));
        GameRegistry.registerItem(teleporter2, teleporter2.func_77658_a().substring(5));
        GameRegistry.registerItem(goodTurret, goodTurret.func_77658_a().substring(5));
        GameRegistry.registerItem(goodTurret2, goodTurret2.func_77658_a().substring(5));
        GameRegistry.registerItem(goodTurret3, goodTurret3.func_77658_a().substring(5));
        GameRegistry.registerItem(malgrum, malgrum.func_77658_a().substring(5));
        GameRegistry.registerItem(malgrumSeeds, malgrumSeeds.func_77658_a().substring(5));
        GameRegistry.registerItem(pleasantBladeBrew, pleasantBladeBrew.func_77658_a().substring(5));
        GameRegistry.registerItem(pleasantBladeFlower, pleasantBladeFlower.func_77658_a().substring(5));
        GameRegistry.registerItem(pleasantBladeLeaf, pleasantBladeLeaf.func_77658_a().substring(5));
        GameRegistry.registerItem(pleasantBladeSeed, pleasantBladeSeed.func_77658_a().substring(5));
        GameRegistry.registerItem(chaff, chaff.func_77658_a().substring(5));
        GameRegistry.registerItem(goldenPotatoe, goldenPotatoe.func_77658_a().substring(5));
        GameRegistry.registerItem(goldenBread, goldenBread.func_77658_a().substring(5));
        GameRegistry.registerItem(goldenCookie, goldenCookie.func_77658_a().substring(5));
        GameRegistry.registerItem(goldenMelon, goldenMelon.func_77658_a().substring(5));
        GameRegistry.registerItem(goldenPumpkinPie, goldenPumpkinPie.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondApple, diamondApple.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondPotatoe, diamondPotatoe.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondBread, diamondBread.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondCookie, diamondCookie.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondMelon, diamondMelon.func_77658_a().substring(5));
        GameRegistry.registerItem(diamondPumpkinPie, diamondPumpkinPie.func_77658_a().substring(5));
        GameRegistry.registerItem(witherSkeletonSpawner, witherSkeletonSpawner.func_77658_a().substring(5));
        GameRegistry.registerItem(eggIronGolemBetter, eggIronGolemBetter.func_77658_a().substring(5));
        GameRegistry.registerItem(eggSnowGolemTitan, eggSnowGolemTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggSlimeTitan, eggSlimeTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggMagmaCubeTitan, eggMagmaCubeTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggOmegafish, eggOmegafish.func_77658_a().substring(5));
        GameRegistry.registerItem(eggCaveSpiderTitan, eggCaveSpiderTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggSpiderTitan, eggSpiderTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggSpiderJockeyTitan, eggSpiderJockeyTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggZombieTitan, eggZombieTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggSkeletonTitan, eggSkeletonTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggCreeperTitan, eggCreeperTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggChargedCreeperTitan, eggChargedCreeperTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggZombiePigmanTitan, eggZombiePigmanTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggBlazeTitan, eggBlazeTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggWitherSkeletonTitan, eggWitherSkeletonTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggWitherJockeyTitan, eggWitherJockeyTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggEnderColossus, eggEnderColossus.func_77658_a().substring(5));
        GameRegistry.registerItem(eggGhastTitan, eggGhastTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggUltimaIronGolemTitan, eggUltimaIronGolemTitan.func_77658_a().substring(5));
        GameRegistry.registerItem(eggWitherzilla, eggWitherzilla.func_77658_a().substring(5));
        if (Loader.isModLoaded("OreSpawn")) {
            OverlordScorpionEgg = new ItemSpawnEggTitans("eggoverlordscorpion", 384);
            MethuselahKrakenEgg = new ItemSpawnEggTitans("eggelderkraken", 385);
            GameRegistry.registerItem(OverlordScorpionEgg, OverlordScorpionEgg.func_77658_a().substring(5));
            GameRegistry.registerItem(MethuselahKrakenEgg, MethuselahKrakenEgg.func_77658_a().substring(5));
        }

    }
}
