//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntityCreeperTitan;
import net.minecraft.util.MathHelper;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelCreeperTitan extends ModelBase {
    public ModelRenderer BottomBody;
    public ModelRenderer Rightfrontupperleg;
    public ModelRenderer Rightbackupperleg;
    public ModelRenderer Leftfrontupperleg;
    public ModelRenderer Leftbackupperleg;
    public ModelRenderer BottomMiddle;
    public ModelRenderer BottomTop;
    public ModelRenderer Head;
    public ModelRenderer Rightfrontcalf;
    public ModelRenderer Rightfrontfoot;
    public ModelRenderer Rightbackcalf;
    public ModelRenderer Rightbackfoot;
    public ModelRenderer Leftfrontcalf;
    public ModelRenderer Leftfrontfoot;
    public ModelRenderer Leftbackcalf;
    public ModelRenderer Leftbackfoot;
    private Animator animator;

    public ModelCreeperTitan() {
        this(0.0F);
    }

    public ModelCreeperTitan(float p_i1147_1_) {
        this.field_78090_t = 64;
        this.field_78089_u = 64;
        this.Leftbackfoot = new ModelRenderer(this, 0, 24);
        this.Leftbackfoot.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Leftbackfoot.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Leftfrontupperleg = new ModelRenderer(this, 0, 16);
        this.Leftfrontupperleg.func_78793_a(3.0F, 16.0F, -1.0F);
        this.Leftfrontupperleg.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Rightbackcalf = new ModelRenderer(this, 0, 16);
        this.Rightbackcalf.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Rightbackcalf.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Rightbackupperleg = new ModelRenderer(this, 0, 16);
        this.Rightbackupperleg.func_78793_a(-3.0F, 16.0F, 1.0F);
        this.Rightbackupperleg.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Leftfrontcalf = new ModelRenderer(this, 0, 16);
        this.Leftfrontcalf.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Leftfrontcalf.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.BottomTop = new ModelRenderer(this, 16, 16);
        this.BottomTop.func_78793_a(0.0F, -4.0F, 0.0F);
        this.BottomTop.func_78790_a(-4.0F, -4.0F, -2.0F, 8, 4, 4, p_i1147_1_);
        this.Head = new ModelRenderer(this, 0, 0);
        this.Head.func_78793_a(0.0F, -4.0F, 0.0F);
        this.Head.func_78790_a(-4.0F, -8.0F, -4.0F, 8, 8, 8, p_i1147_1_);
        this.BottomBody = new ModelRenderer(this, 16, 32);
        this.BottomBody.func_78793_a(0.0F, 16.0F, 0.0F);
        this.BottomBody.func_78790_a(-4.0F, -2.0F, -2.0F, 8, 4, 4, p_i1147_1_);
        this.Leftbackcalf = new ModelRenderer(this, 0, 16);
        this.Leftbackcalf.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Leftbackcalf.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Leftbackupperleg = new ModelRenderer(this, 0, 16);
        this.Leftbackupperleg.func_78793_a(3.0F, 16.0F, 1.0F);
        this.Leftbackupperleg.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Rightbackfoot = new ModelRenderer(this, 0, 24);
        this.Rightbackfoot.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Rightbackfoot.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Rightfrontupperleg = new ModelRenderer(this, 0, 16);
        this.Rightfrontupperleg.func_78793_a(-3.0F, 16.0F, -1.0F);
        this.Rightfrontupperleg.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.BottomMiddle = new ModelRenderer(this, 16, 24);
        this.BottomMiddle.func_78793_a(0.0F, -2.0F, 0.0F);
        this.BottomMiddle.func_78790_a(-4.0F, -4.0F, -2.0F, 8, 4, 4, p_i1147_1_);
        this.Leftfrontfoot = new ModelRenderer(this, 0, 24);
        this.Leftfrontfoot.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Leftfrontfoot.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Rightfrontcalf = new ModelRenderer(this, 0, 16);
        this.Rightfrontcalf.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Rightfrontcalf.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Rightfrontfoot = new ModelRenderer(this, 0, 24);
        this.Rightfrontfoot.func_78793_a(0.0F, 3.5F, 0.0F);
        this.Rightfrontfoot.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 4, 4, p_i1147_1_);
        this.Leftbackcalf.func_78792_a(this.Leftbackfoot);
        this.Rightbackupperleg.func_78792_a(this.Rightbackcalf);
        this.Leftfrontupperleg.func_78792_a(this.Leftfrontcalf);
        this.BottomMiddle.func_78792_a(this.BottomTop);
        this.BottomTop.func_78792_a(this.Head);
        this.Leftbackupperleg.func_78792_a(this.Leftbackcalf);
        this.Rightbackcalf.func_78792_a(this.Rightbackfoot);
        this.BottomBody.func_78792_a(this.BottomMiddle);
        this.Leftfrontcalf.func_78792_a(this.Leftfrontfoot);
        this.Rightfrontupperleg.func_78792_a(this.Rightfrontcalf);
        this.Rightfrontcalf.func_78792_a(this.Rightfrontfoot);
        this.animator = new Animator(this);
    }

    public void func_78088_a(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
        this.Leftfrontupperleg.func_78785_a(f5);
        this.Rightbackupperleg.func_78785_a(f5);
        this.BottomBody.func_78785_a(f5);
        this.Leftbackupperleg.func_78785_a(f5);
        this.Rightfrontupperleg.func_78785_a(f5);
    }

    public void setAngles() {
        float f = 16.1F;
        this.Rightbackupperleg.func_78793_a(-3.0F, f, 1.0F);
        this.Leftfrontupperleg.func_78793_a(3.0F, f, -1.0F);
        this.BottomBody.func_78793_a(0.0F, f, 0.0F);
        this.Leftbackupperleg.func_78793_a(3.0F, f, 1.0F);
        this.Rightfrontupperleg.func_78793_a(-3.0F, f, -1.0F);
        this.Rightbackcalf.field_78795_f = ((float)Math.PI / 4F);
        this.Leftfrontcalf.field_78795_f = ((float)Math.PI / 4F);
        this.Leftbackcalf.field_78795_f = ((float)Math.PI / 4F);
        this.Rightfrontcalf.field_78795_f = ((float)Math.PI / 4F);
        this.Rightbackfoot.field_78795_f = ((float)Math.PI / 6F);
        this.Leftfrontfoot.field_78795_f = ((float)Math.PI / 6F);
        this.Rightfrontfoot.field_78795_f = ((float)Math.PI / 6F);
        this.Leftbackfoot.field_78795_f = ((float)Math.PI / 6F);
        this.Leftfrontupperleg.field_78795_f = -1.3089969F;
        this.Leftfrontupperleg.field_78796_g = -0.525F;
        this.Rightbackupperleg.field_78796_g = 2.625F;
        this.Rightbackupperleg.field_78795_f = -1.3089969F;
        this.Leftbackupperleg.field_78796_g = -2.625F;
        this.Leftbackupperleg.field_78795_f = -1.3089969F;
        this.Rightfrontupperleg.field_78795_f = -1.3089969F;
        this.Rightfrontupperleg.field_78796_g = 0.525F;
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animator.update(entity);
        this.setAngles();
        EntityCreeperTitan entitytitan = (EntityCreeperTitan)entity;
        float f6 = MathHelper.func_76134_b(f2 * 0.1F);
        if (entitytitan.deathTicks <= 0) {
            float faceYaw = f3 * (float)Math.PI / 180.0F;
            float facePitch = f4 * (float)Math.PI / 180.0F;
            this.BottomBody.field_78808_h = MathHelper.func_76134_b(f * 0.25F) * 0.3F * f1;
            this.BottomMiddle.field_78808_h = MathHelper.func_76134_b(f * 0.25F - 1.0F) * 0.3F * f1;
            this.BottomTop.field_78808_h = MathHelper.func_76134_b(f * 0.25F - 2.0F) * 0.3F * f1;
            this.Head.field_78808_h = MathHelper.func_76134_b(f * 0.25F - 3.0F) * 0.3F * f1;
            if (entitytitan.getAnimID() == 8 && entitytitan.getAnimTick() > 130 && entitytitan.getAnimTick() < 430) {
                this.BottomMiddle.field_78796_g = MathHelper.func_76134_b(f2 * 0.05F + 2.0F) * 0.2F;
                this.BottomTop.field_78796_g = MathHelper.func_76134_b(f2 * 0.05F + 1.0F) * 0.2F;
                this.Head.field_78796_g = MathHelper.func_76134_b(f2 * 0.05F) * 0.2F;
                this.BottomMiddle.field_78795_f = (-0.025F + -0.0125F * MathHelper.func_76134_b(f2 * 0.1F - 2.0F)) * (float)Math.PI;
                this.BottomTop.field_78795_f = (0.0125F + 0.0125F * MathHelper.func_76134_b(f2 * 0.1F - 1.0F)) * (float)Math.PI;
                this.Head.field_78795_f = (0.0125F + 0.0125F * f6) * (float)Math.PI;
            }

            if (entitytitan.getAnimID() == 13 && entitytitan.getAnimTick() < 5) {
                this.BottomMiddle.field_78795_f = (-0.005F + -0.005F * MathHelper.func_76134_b(f2 * 0.1F - 2.0F)) * (float)Math.PI;
                this.BottomTop.field_78795_f = (0.005F + 0.005F * MathHelper.func_76134_b(f2 * 0.1F - 1.0F)) * (float)Math.PI;
                this.Head.field_78795_f = (0.005F + 0.005F * f6) * (float)Math.PI;
            }

            if (this.field_78093_q) {
                this.Rightbackupperleg.func_78793_a(-3.0F, 21.0F, 1.0F);
                this.Leftfrontupperleg.func_78793_a(3.0F, 21.0F, -1.0F);
                this.BottomBody.func_78793_a(0.0F, 21.0F, 0.0F);
                this.Leftbackupperleg.func_78793_a(3.0F, 21.0F, 1.0F);
                this.Rightfrontupperleg.func_78793_a(-3.0F, 21.0F, -1.0F);
                this.Leftfrontupperleg.field_78795_f = -1.6F;
                this.Leftbackupperleg.field_78795_f = -1.6F;
                this.Rightfrontupperleg.field_78795_f = -1.6F;
                this.Rightbackupperleg.field_78795_f = -1.6F;
                this.Leftfrontupperleg.field_78796_g = -0.725F;
                this.Leftbackupperleg.field_78796_g = -2.25F;
                this.Rightfrontupperleg.field_78796_g = 0.725F;
                this.Rightbackupperleg.field_78796_g = 2.25F;
                this.Leftbackcalf.field_78795_f = 1.0F;
                this.Leftfrontcalf.field_78795_f = 1.0F;
                this.Rightbackcalf.field_78795_f = 1.0F;
                this.Rightfrontcalf.field_78795_f = 1.0F;
            } else if (entitytitan.getAnimID() == 0) {
                this.BottomMiddle.field_78795_f = (-0.025F + -0.0125F * MathHelper.func_76134_b(f2 * 0.1F - 2.0F)) * (float)Math.PI;
                this.BottomTop.field_78795_f = (0.0125F + 0.0125F * MathHelper.func_76134_b(f2 * 0.1F - 1.0F)) * (float)Math.PI;
                this.Head.field_78795_f = (0.0125F + 0.0125F * f6) * (float)Math.PI;
                this.Leftfrontupperleg.field_78795_f = -1.3089969F + MathHelper.func_76134_b(f * 0.25F + 0.25F) * 0.75F * f1;
                this.Leftbackupperleg.field_78795_f = -1.3089969F + MathHelper.func_76134_b(f * 0.25F + 3.3915927F) * 0.75F * f1;
                this.Rightfrontupperleg.field_78795_f = -1.3089969F + MathHelper.func_76134_b(f * 0.25F + 3.3915927F) * 0.75F * f1;
                this.Rightbackupperleg.field_78795_f = -1.3089969F + MathHelper.func_76134_b(f * 0.25F + 0.25F) * 0.75F * f1;
                this.Leftfrontupperleg.field_78796_g = -0.525F + MathHelper.func_76134_b(f * 0.25F + 2.6415927F) * 0.5F * f1;
                this.Leftbackupperleg.field_78796_g = -2.625F + MathHelper.func_76134_b(f * 0.25F - 0.5F) * 0.5F * f1;
                this.Rightfrontupperleg.field_78796_g = 0.525F - MathHelper.func_76134_b(f * 0.25F - 0.75F) * 0.5F * f1;
                this.Rightbackupperleg.field_78796_g = 2.625F - MathHelper.func_76134_b(f * 0.25F + 2.6415927F) * 0.5F * f1;
                this.Leftbackcalf.field_78795_f = ((float)Math.PI / 4F) + MathHelper.func_76134_b(f * 0.25F) * 0.5F * f1;
                this.Leftfrontcalf.field_78795_f = ((float)Math.PI / 4F) + MathHelper.func_76134_b(f * 0.25F + (float)Math.PI) * 0.5F * f1;
                this.Rightbackcalf.field_78795_f = ((float)Math.PI / 4F) + MathHelper.func_76134_b(f * 0.25F + (float)Math.PI) * 0.5F * f1;
                this.Rightfrontcalf.field_78795_f = ((float)Math.PI / 4F) + MathHelper.func_76134_b(f * 0.25F) * 0.5F * f1;
                if (this.Leftfrontupperleg.field_78795_f > -1.3089969F) {
                    this.Leftfrontupperleg.field_78795_f = -1.3089969F;
                }

                if (this.Rightfrontupperleg.field_78795_f > -1.3089969F) {
                    this.Rightfrontupperleg.field_78795_f = -1.3089969F;
                }

                if (this.Rightbackupperleg.field_78795_f > -1.3089969F) {
                    this.Rightbackupperleg.field_78795_f = -1.3089969F;
                }

                if (this.Leftbackupperleg.field_78795_f > -1.3089969F) {
                    this.Leftbackupperleg.field_78795_f = -1.3089969F;
                }

                if (this.Rightbackcalf.field_78795_f < ((float)Math.PI / 4F)) {
                    this.Rightbackcalf.field_78795_f = ((float)Math.PI / 4F);
                }

                if (this.Rightfrontcalf.field_78795_f < ((float)Math.PI / 4F)) {
                    this.Rightfrontcalf.field_78795_f = ((float)Math.PI / 4F);
                }

                if (this.Leftbackcalf.field_78795_f < ((float)Math.PI / 4F)) {
                    this.Leftbackcalf.field_78795_f = ((float)Math.PI / 4F);
                }

                if (this.Leftfrontcalf.field_78795_f < ((float)Math.PI / 4F)) {
                    this.Leftfrontcalf.field_78795_f = ((float)Math.PI / 4F);
                }

                if (this.Rightbackcalf.field_78795_f < ((float)Math.PI / 4F)) {
                    this.Rightbackcalf.field_78795_f = ((float)Math.PI / 4F);
                }

                if (this.Rightfrontcalf.field_78795_f < ((float)Math.PI / 4F)) {
                    this.Rightfrontcalf.field_78795_f = ((float)Math.PI / 4F);
                }
            }

            ModelRenderer var10000 = this.Head;
            var10000.field_78795_f += facePitch * 0.3F;
            var10000 = this.Head;
            var10000.field_78796_g += faceYaw * 0.3F;
            var10000 = this.BottomTop;
            var10000.field_78795_f += facePitch * 0.3F;
            var10000 = this.BottomTop;
            var10000.field_78796_g += faceYaw * 0.3F;
            var10000 = this.BottomMiddle;
            var10000.field_78795_f += facePitch * 0.3F;
            var10000 = this.BottomMiddle;
            var10000.field_78796_g += faceYaw * 0.3F;
            if (!entitytitan.field_70122_E && !this.field_78093_q) {
                this.BottomBody.field_78808_h = 0.0F;
                this.BottomMiddle.field_78808_h = 0.0F;
                this.BottomTop.field_78808_h = 0.0F;
                this.Head.field_78808_h = 0.0F;
                var10000 = this.Head;
                var10000.field_78795_f -= entitytitan.field_70721_aZ;
                var10000 = this.BottomBody;
                var10000.field_78795_f += entitytitan.field_70721_aZ;
                this.Leftfrontupperleg.field_78796_g = -0.25F;
                this.Rightbackupperleg.field_78796_g = 2.75F;
                this.Leftbackupperleg.field_78796_g = -2.75F;
                this.Rightfrontupperleg.field_78796_g = 0.25F;
                this.Rightbackupperleg.field_78795_f = -2.0F - MathHelper.func_76134_b(f2 * 0.2F) * 0.25F - (float)(entitytitan.field_70181_x / (double)5.0F) - entitytitan.field_70721_aZ;
                this.Leftbackupperleg.field_78795_f = -2.0F - MathHelper.func_76134_b(f2 * 0.2F - (float)Math.PI) * 0.25F - (float)(entitytitan.field_70181_x / (double)5.0F) - entitytitan.field_70721_aZ;
                this.Rightfrontupperleg.field_78795_f = -2.0F - MathHelper.func_76134_b(f2 * 0.2F) * 0.25F - (float)(entitytitan.field_70181_x / (double)5.0F) + entitytitan.field_70721_aZ;
                this.Leftfrontupperleg.field_78795_f = -2.0F - MathHelper.func_76134_b(f2 * 0.2F - (float)Math.PI) * 0.25F - (float)(entitytitan.field_70181_x / (double)5.0F) + entitytitan.field_70721_aZ;
            }

            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0:
                        this.animateAntiTitanAttack1();
                        break;
                    case 1:
                        this.animateAntiTitanAttack2();
                        break;
                    case 2:
                        this.animateAntiTitanAttack3();
                        break;
                    case 3:
                        this.animateAntiTitanAttack4();
                }
            }

            this.animateStunned();
            this.animateThunderClap();
            this.animateSpit();
            this.animateKick();
            this.animateStomp();
            this.animateAttackStomp();
            this.animateHeadSlam();
            this.animateBirth();
        } else {
            this.animateDeath();
        }

    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, -3.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -4.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -4.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.rotate(this.Head, -1.0F, -1.2F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.75F, 0.6F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.75F, 0.6F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.75F, -0.75F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -2.25F, -0.75F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -2.25F, 0.75F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, 1.0F, -8.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 1.0F, -8.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 1.0F, -8.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.rotate(this.Head, 0.5F, 0.75F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.75F, 0.75F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.75F, 0.5F, 0.0F);
        this.animator.rotate(this.BottomBody, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, -3.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -4.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -4.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.rotate(this.Head, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 1.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, -0.75F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.5F, 0.75F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, -8.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.rotate(this.Head, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, -1.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 4.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -4.0F, -0.5F, -1.3F);
        this.animator.rotate(this.Leftfrontupperleg, -4.0F, 0.5F, 1.3F);
        this.animator.rotate(this.Rightbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, -8.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, -8.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, -8.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, -8.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, -8.0F);
        this.animator.rotate(this.Head, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, -1.3F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 1.3F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, -3.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -4.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -4.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -2.0F, 4.0F);
        this.animator.rotate(this.Head, -1.0F, 1.2F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.75F, -0.6F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.75F, -0.6F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.75F, 0.75F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -2.25F, -0.75F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -2.25F, 0.75F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, 1.0F, -8.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 1.0F, -8.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 1.0F, -8.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, -8.0F);
        this.animator.rotate(this.Head, 0.5F, -0.75F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.75F, -0.75F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.75F, -0.5F, 0.0F);
        this.animator.rotate(this.BottomBody, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAttackStomp() {
        this.animator.setAnim(2);
        this.animator.startPhase(25);
        this.animator.rotate(this.Head, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -2.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.5F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.25F, 0.5F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.25F, 0.5F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, 0.75F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -1.5F, -0.75F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, -0.5F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.25F, -0.5F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.25F, -0.5F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.75F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.0F, -0.75F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -2.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, -0.5F);
        this.animator.rotate(this.BottomMiddle, -0.5F, -0.25F, -0.5F);
        this.animator.rotate(this.BottomBody, -0.5F, -0.25F, -0.5F);
        this.animator.rotate(this.Leftfrontupperleg, -1.5F, -0.75F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -1.5F, 0.75F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.5F);
        this.animator.rotate(this.BottomMiddle, 0.5F, -0.25F, 0.5F);
        this.animator.rotate(this.BottomBody, 0.5F, -0.25F, 0.5F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, -0.75F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.0F, 0.75F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.5F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0F, 1.0F, -3.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 1.0F, -2.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 1.0F, -2.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, -2.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, -2.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateHeadSlam() {
        this.animator.setAnim(4);
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateKick() {
        this.animator.setAnim(5);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, -1.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.25F, 0.5F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.25F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, 1.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.75F, -1.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.75F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -1.0F, 1.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.25F, -1.5F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.25F, -0.75F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.25F, -0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSpit() {
        this.animator.setAnim(6);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.25F, 0.0F, 0.0F);
        this.animator.move(this.BottomBody, 0.0F, -0.5F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.1F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.1F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateThunderClap() {
        this.animator.setAnim(7);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.5F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.35F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.35F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.25F, -0.5F, -1.3F);
        this.animator.rotate(this.Leftfrontupperleg, -1.25F, 0.5F, 1.3F);
        this.animator.rotate(this.Rightbackupperleg, 0.35F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.35F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -2.5F, -0.5F, -1.3F);
        this.animator.rotate(this.Leftfrontupperleg, -2.5F, 0.5F, 1.3F);
        this.animator.rotate(this.Rightbackupperleg, 0.35F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.35F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.75F, -0.5F, -1.3F);
        this.animator.rotate(this.Leftfrontupperleg, -0.75F, 0.5F, 1.3F);
        this.animator.rotate(this.Rightbackupperleg, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0F, 1.0F, -3.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 1.0F, -2.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 1.0F, -2.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, -2.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, -2.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.1F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(50);
    }

    private void animateStunned() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 1.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.2F, 0.25F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.2F, -0.25F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -3.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -3.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, -1.0F, 1.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.25F, 0.35F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.25F, -0.35F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0F, -1.0F, 1.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, -2.0F, 1.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 1.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.25F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, -0.25F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(300);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, 1.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, -4.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.25F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, -0.25F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 1.0F, 0.0F, 2.0F);
        this.animator.rotate(this.Leftbackupperleg, 1.0F, 0.0F, -2.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.rotate(this.Head, 0.25F, 0.25F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.25F, 0.25F, 0.0F);
        this.animator.rotate(this.BottomBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 4.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1720);
        this.animator.resetPhase(0);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 6.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 6.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 6.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -1.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -1.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0F, 6.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 6.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 6.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, -0.25F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, -0.3F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, 0.1F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, 0.2F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.BottomTop, 0.25F, 0.0F, 0.3F);
        this.animator.rotate(this.BottomMiddle, 0.25F, 0.0F, -0.1F);
        this.animator.rotate(this.BottomBody, 0.25F, 0.0F, -0.2F);
        this.animator.rotate(this.Rightfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackupperleg, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightfrontfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Leftbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackcalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Rightbackfoot, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }
}
