//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntitySpiderTitan;
import net.minecraft.util.MathHelper;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelSpiderTitan extends ModelBase {
    public ModelRenderer Thorax;
    public ModelRenderer Head;
    public ModelRenderer Abdoman;
    public ModelRenderer Frontleftupperarm;
    public ModelRenderer Frontrightupperarm;
    public ModelRenderer Frontleftupperleg;
    public ModelRenderer Frontrightupperleg;
    public ModelRenderer Backrightupperleg1;
    public ModelRenderer Backrightupperleg2;
    public ModelRenderer Backleftupperleg1;
    public ModelRenderer Backleftupperleg2;
    public ModelRenderer Frontleftlowerarm;
    public ModelRenderer Frontrightlowerarm;
    public ModelRenderer Frontleftlowerleg;
    public ModelRenderer Frontrightlowerleg;
    public ModelRenderer Backrightlowerleg1;
    public ModelRenderer Backrightlowerleg2;
    public ModelRenderer Backleftlowerleg1;
    public ModelRenderer Backleftlowerleg2;
    private Animator animator;

    public ModelSpiderTitan() {
        this(0.0F);
    }

    public ModelSpiderTitan(float p_i1147_1_) {
        this.field_78090_t = 64;
        this.field_78089_u = 64;
        this.Head = new ModelRenderer(this, 0, 0);
        this.Head.func_78793_a(0.0F, 0.0F, -3.0F);
        this.Head.func_78790_a(-4.0F, -4.0F, -8.0F, 8, 8, 8, p_i1147_1_);
        this.Backleftlowerleg1 = new ModelRenderer(this, 32, 10);
        this.Backleftlowerleg1.field_78809_i = true;
        this.Backleftlowerleg1.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Backleftlowerleg1.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Abdoman = new ModelRenderer(this, 0, 28);
        this.Abdoman.func_78793_a(0.0F, 0.0F, 3.0F);
        this.Abdoman.func_78790_a(-5.0F, -4.0F, 0.0F, 10, 8, 12, p_i1147_1_);
        this.Backrightupperleg1 = new ModelRenderer(this, 32, 0);
        this.Backrightupperleg1.func_78793_a(-3.0F, 0.0F, 1.0F);
        this.Backrightupperleg1.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Backleftupperleg2 = new ModelRenderer(this, 32, 0);
        this.Backleftupperleg2.field_78809_i = true;
        this.Backleftupperleg2.func_78793_a(3.0F, 0.0F, 2.0F);
        this.Backleftupperleg2.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Thorax = new ModelRenderer(this, 0, 16);
        this.Thorax.func_78793_a(0.0F, 15.0F, 0.0F);
        this.Thorax.func_78790_a(-3.0F, -3.0F, -3.0F, 6, 6, 6, p_i1147_1_);
        this.Frontleftlowerarm = new ModelRenderer(this, 32, 10);
        this.Frontleftlowerarm.field_78809_i = true;
        this.Frontleftlowerarm.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Frontleftlowerarm.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Backrightupperleg2 = new ModelRenderer(this, 32, 0);
        this.Backrightupperleg2.func_78793_a(-3.0F, 0.0F, 2.0F);
        this.Backrightupperleg2.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontleftupperleg = new ModelRenderer(this, 32, 0);
        this.Frontleftupperleg.field_78809_i = true;
        this.Frontleftupperleg.func_78793_a(3.0F, 0.0F, -1.0F);
        this.Frontleftupperleg.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Backrightlowerleg2 = new ModelRenderer(this, 32, 10);
        this.Backrightlowerleg2.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Backrightlowerleg2.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontrightupperleg = new ModelRenderer(this, 32, 0);
        this.Frontrightupperleg.func_78793_a(-3.0F, 0.0F, -1.0F);
        this.Frontrightupperleg.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontrightlowerarm = new ModelRenderer(this, 32, 10);
        this.Frontrightlowerarm.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Frontrightlowerarm.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontleftlowerleg = new ModelRenderer(this, 32, 10);
        this.Frontleftlowerleg.field_78809_i = true;
        this.Frontleftlowerleg.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Frontleftlowerleg.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Backleftlowerleg2 = new ModelRenderer(this, 32, 10);
        this.Backleftlowerleg2.field_78809_i = true;
        this.Backleftlowerleg2.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Backleftlowerleg2.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontleftupperarm = new ModelRenderer(this, 32, 0);
        this.Frontleftupperarm.field_78809_i = true;
        this.Frontleftupperarm.func_78793_a(3.0F, 0.0F, -2.0F);
        this.Frontleftupperarm.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontrightupperarm = new ModelRenderer(this, 32, 0);
        this.Frontrightupperarm.func_78793_a(-3.0F, 0.0F, -2.0F);
        this.Frontrightupperarm.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Backleftupperleg1 = new ModelRenderer(this, 32, 0);
        this.Backleftupperleg1.field_78809_i = true;
        this.Backleftupperleg1.func_78793_a(3.0F, 0.0F, 1.0F);
        this.Backleftupperleg1.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Frontrightlowerleg = new ModelRenderer(this, 32, 10);
        this.Frontrightlowerleg.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Frontrightlowerleg.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Backrightlowerleg1 = new ModelRenderer(this, 32, 10);
        this.Backrightlowerleg1.func_78793_a(0.0F, 8.0F, 0.0F);
        this.Backrightlowerleg1.func_78790_a(-1.0F, 0.0F, -1.0F, 2, 8, 2, p_i1147_1_);
        this.Thorax.func_78792_a(this.Head);
        this.Backleftupperleg1.func_78792_a(this.Backleftlowerleg1);
        this.Thorax.func_78792_a(this.Abdoman);
        this.Thorax.func_78792_a(this.Backrightupperleg1);
        this.Thorax.func_78792_a(this.Backleftupperleg2);
        this.Frontleftupperarm.func_78792_a(this.Frontleftlowerarm);
        this.Thorax.func_78792_a(this.Backrightupperleg2);
        this.Thorax.func_78792_a(this.Frontleftupperleg);
        this.Backrightupperleg2.func_78792_a(this.Backrightlowerleg2);
        this.Thorax.func_78792_a(this.Frontrightupperleg);
        this.Frontrightupperarm.func_78792_a(this.Frontrightlowerarm);
        this.Frontleftupperleg.func_78792_a(this.Frontleftlowerleg);
        this.Backleftupperleg2.func_78792_a(this.Backleftlowerleg2);
        this.Thorax.func_78792_a(this.Frontleftupperarm);
        this.Thorax.func_78792_a(this.Frontrightupperarm);
        this.Thorax.func_78792_a(this.Backleftupperleg1);
        this.Frontrightupperleg.func_78792_a(this.Frontrightlowerleg);
        this.Backrightupperleg1.func_78792_a(this.Backrightlowerleg1);
        this.animator = new Animator(this);
    }

    public void func_78088_a(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntitySpiderTitan spiderTitan = (EntitySpiderTitan)entity;
        this.animate(spiderTitan, f, f1, f2, f3, f4, f5);
        this.Thorax.func_78785_a(f5);
    }

    public void setAngles() {
        this.Thorax.field_78797_d = 15.0F;
        this.Thorax.field_78800_c = 0.0F;
        this.Thorax.field_78798_e = 0.0F;
        this.Head.field_78795_f = 0.0F;
        this.Thorax.field_78795_f = 0.0F;
        this.Abdoman.field_78795_f = 0.0F;
        this.Frontrightupperarm.field_78795_f = -1.2217305F;
        this.Frontrightupperarm.field_78796_g = 0.87266463F;
        this.Frontleftupperarm.field_78795_f = -1.2217305F;
        this.Frontleftupperarm.field_78796_g = -0.87266463F;
        this.Frontrightlowerarm.field_78795_f = 0.475F;
        this.Frontleftlowerarm.field_78795_f = 0.475F;
        this.Frontleftupperleg.field_78795_f = -1.2217305F;
        this.Frontleftupperleg.field_78796_g = -1.3089969F;
        this.Frontrightupperleg.field_78795_f = -1.2217305F;
        this.Frontrightupperleg.field_78796_g = 1.3089969F;
        this.Frontleftlowerleg.field_78795_f = 0.475F;
        this.Frontrightlowerleg.field_78795_f = 0.475F;
        this.Backleftupperleg1.field_78795_f = -1.2217305F;
        this.Backleftupperleg1.field_78796_g = -1.8325957F;
        this.Backrightupperleg1.field_78795_f = -1.2217305F;
        this.Backrightupperleg1.field_78796_g = 1.8325957F;
        this.Backleftlowerleg1.field_78795_f = 0.475F;
        this.Backrightlowerleg1.field_78795_f = 0.475F;
        this.Backleftupperleg2.field_78795_f = -1.2217305F;
        this.Backleftupperleg2.field_78796_g = -2.1816616F;
        this.Backrightupperleg2.field_78795_f = -1.2217305F;
        this.Backrightupperleg2.field_78796_g = 2.1816616F;
        this.Backleftlowerleg2.field_78795_f = 0.475F;
        this.Backrightlowerleg2.field_78795_f = 0.475F;
    }

    public void animate(EntitySpiderTitan spider, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animator.update(spider);
        this.setAngles();
        if (spider.deathTicks <= 0) {
            if (this.field_78093_q) {
                this.Frontrightupperarm.field_78796_g = 0.87266463F;
                this.Frontleftupperarm.field_78796_g = -0.87266463F;
                this.Frontrightupperleg.field_78796_g = 1.3089969F;
                this.Frontleftupperleg.field_78796_g = -1.3089969F;
                this.Backrightupperleg1.field_78796_g = 1.8325957F;
                this.Backleftupperleg1.field_78796_g = -1.8325957F;
                this.Backrightupperleg2.field_78796_g = 2.1816616F;
                this.Backleftupperleg2.field_78796_g = -2.1816616F;
                this.Frontrightupperarm.field_78795_f = -0.8F;
                this.Frontleftupperarm.field_78795_f = -0.8F;
                this.Frontrightupperleg.field_78795_f = -0.8F;
                this.Frontleftupperleg.field_78795_f = -0.8F;
                this.Backrightupperleg1.field_78795_f = -0.8F;
                this.Backleftupperleg1.field_78795_f = -0.8F;
                this.Backrightupperleg2.field_78795_f = -0.8F;
                this.Backleftupperleg2.field_78795_f = -0.8F;
            } else if (spider.getAnimID() == 0) {
                this.Frontrightupperarm.field_78796_g = 0.87266463F + MathHelper.func_76134_b(f * 0.5F + 2.0F) * 0.3F * f1;
                this.Frontleftupperarm.field_78796_g = -0.87266463F + MathHelper.func_76134_b(f * 0.5F + 4.0F) * 0.3F * f1;
                this.Frontrightupperleg.field_78796_g = 1.3089969F + MathHelper.func_76134_b(f * 0.5F + 6.0F) * 0.3F * f1;
                this.Frontleftupperleg.field_78796_g = -1.3089969F + MathHelper.func_76134_b(f * 0.5F) * 0.3F * f1;
                this.Backrightupperleg1.field_78796_g = 1.8325957F + MathHelper.func_76134_b(f * 0.5F + 6.0F) * 0.3F * f1;
                this.Backleftupperleg1.field_78796_g = -1.8325957F + MathHelper.func_76134_b(f * 0.5F + 4.0F) * 0.3F * f1;
                this.Backrightupperleg2.field_78796_g = 2.1816616F + MathHelper.func_76134_b(f * 0.5F + 2.0F) * 0.3F * f1;
                this.Backleftupperleg2.field_78796_g = -2.1816616F + MathHelper.func_76134_b(f * 0.5F) * 0.3F * f1;
                this.Frontrightupperarm.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F + 2.0F) * 0.15F * f1;
                this.Frontleftupperarm.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F + 4.0F) * 0.15F * f1;
                this.Frontrightupperleg.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F + 6.0F) * 0.15F * f1;
                this.Frontleftupperleg.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F) * 0.15F * f1;
                this.Backrightupperleg1.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F + 6.0F) * 0.15F * f1;
                this.Backleftupperleg1.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F + 4.0F) * 0.15F * f1;
                this.Backrightupperleg2.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F + 2.0F) * 0.15F * f1;
                this.Backleftupperleg2.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f * 0.5F) * 0.15F * f1;
            }

            if (!spider.field_70122_E && !this.field_78093_q) {
                ModelRenderer var10000 = this.Abdoman;
                var10000.field_78795_f -= MathHelper.func_76134_b(f * 0.35F - 1.5F) * 0.1F * f1 - 0.25F + spider.field_70721_aZ;
                this.Frontrightupperarm.field_78796_g = 0.5F;
                this.Frontleftupperarm.field_78796_g = -0.5F;
                this.Frontrightupperleg.field_78796_g = 1.4F + spider.field_70721_aZ;
                this.Frontleftupperleg.field_78796_g = -1.4F - spider.field_70721_aZ;
                this.Backrightupperleg1.field_78796_g = 1.8F + spider.field_70721_aZ;
                this.Backleftupperleg1.field_78796_g = -1.8F - spider.field_70721_aZ;
                this.Backrightupperleg2.field_78796_g = 2.0F + spider.field_70721_aZ;
                this.Backleftupperleg2.field_78796_g = -2.0F - spider.field_70721_aZ;
                this.Frontrightupperleg.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f2 * 0.2F) * 0.25F;
                this.Frontleftupperleg.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f2 * 0.2F - 0.5F) * 0.25F;
                this.Backrightupperleg1.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f2 * 0.2F - 1.0F) * 0.25F;
                this.Backleftupperleg1.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f2 * 0.2F - 1.5F) * 0.25F;
                this.Backrightupperleg2.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f2 * 0.2F - 2.0F) * 0.25F;
                this.Backleftupperleg2.field_78795_f = -1.2217305F + MathHelper.func_76134_b(f2 * 0.2F - 2.5F) * 0.25F;
                if (spider.getAnimID() == 0) {
                    this.Frontrightupperarm.field_78795_f = -2.0F;
                    this.Frontleftupperarm.field_78795_f = -2.0F;
                }
            }

            if (spider.getAnimID() == 0) {
                this.Head.field_78795_f = (0.01F + 0.01F * MathHelper.func_76134_b(f2 * 0.1F)) * (float)Math.PI;
                this.Abdoman.field_78795_f = -((0.01F + 0.01F * MathHelper.func_76134_b(f2 * 0.1F)) * (float)Math.PI);
                this.Thorax.field_78797_d = 15.0F - 0.025F * MathHelper.func_76134_b(f2 * 0.1F) * (float)Math.PI;
            }

            if (spider.getAnimID() == 6 && spider.getAnimTick() >= 30 && spider.getAnimTick() < 50) {
                this.Abdoman.field_78795_f = 0.1F * MathHelper.func_76134_b(f2 * 1.0F) * (float)Math.PI;
            }

            if (spider.getAnimID() == 6 && spider.getAnimTick() >= 50 && spider.getAnimTick() < 100) {
                this.Abdoman.field_78795_f = 0.1F * MathHelper.func_76134_b(f2 * 1.5F) * (float)Math.PI;
            }

            float faceYaw = f3 * (float)Math.PI / 180.0F;
            float facePitch = f4 * (float)Math.PI / 180.0F;
            ModelRenderer var10 = this.Head;
            var10.field_78795_f += facePitch * 0.9F;
            var10 = this.Head;
            var10.field_78796_g += faceYaw * 0.9F;
            if (spider.getAnimID() == 1) {
                switch (spider.antiTitanAttackAnimeID) {
                    case 0:
                        this.animateAntiTitanAttack1();
                        break;
                    case 1:
                        this.animateAntiTitanAttack2();
                        break;
                    case 2:
                        this.animateAntiTitanAttack3();
                        break;
                    case 3:
                        this.animateAntiTitanAttack4();
                }
            }

            this.animateBirth();
            this.animateBite();
            this.animateSpit();
            this.animateStomp();
            this.animateSwat();
            this.animateShootLightning();
            this.animateShootWeb();
            this.animateStunned();
            this.animateCrush();
        } else {
            this.animateDeath();
        }

    }

    private void animateBite() {
        this.animator.setAnim(4);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -4.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, -16.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateSpit() {
        this.animator.setAnim(2);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.3F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.05F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.3F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.05F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, -0.5F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -2.0F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -2.0F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.2F, 0.2F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.2F, -0.2F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.2F, -0.2F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.4F, -0.3F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.2F, 0.2F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.4F, 0.3F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.2F, 0.75F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.2F, -0.75F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.2F, -0.75F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.2F, 0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSwat() {
        this.animator.setAnim(5);
        this.animator.startPhase(20);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.0F, -1.0F);
        this.animator.rotate(this.Frontrightlowerarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.4F, -0.5F, 0.1F);
        this.animator.rotate(this.Abdoman, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 0.5F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Frontrightupperarm, 2.0F, -2.0F, -1.0F);
        this.animator.rotate(this.Frontrightlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.4F, 0.5F, -0.1F);
        this.animator.rotate(this.Abdoman, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.0F, -0.1F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, -0.1F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -0.1F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -0.1F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -0.1F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, -0.1F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, -0.1F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, 12.0F);
        this.animator.rotate(this.Frontleftupperarm, -2.0F, 0.9F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -2.0F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.75F, 0.5F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, -12.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.5F, 0.75F, 1.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.5F, -1.75F, 1.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.25F, -0.5F, -0.5F);
        this.animator.rotate(this.Frontrightlowerarm, 0.25F, 0.5F, 0.5F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, 12.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, -12.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 1.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 1.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.5F, 0.5F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 0.0F, 12.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, -12.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, 12.0F);
        this.animator.rotate(this.Frontleftupperarm, -2.0F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -2.0F, -0.9F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 1.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 1.75F, 0.3F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.75F, -0.5F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0F, 0.0F, -12.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.5F, -0.75F, -1.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.5F, 1.75F, -1.0F);
        this.animator.rotate(this.Frontleftlowerarm, -0.5F, 0.5F, -0.5F);
        this.animator.rotate(this.Frontrightlowerarm, -0.5F, -0.5F, 0.5F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateShootWeb() {
        this.animator.setAnim(6);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.3F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.05F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -2.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -4.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, -0.6F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.6F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, -0.3F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.3F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.resetPhase(40);
    }

    private void animateShootLightning() {
        this.animator.setAnim(7);
        this.animator.startPhase(50);
        this.animator.rotate(this.Head, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -1.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -4.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, -0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -4.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -2.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -4.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(50);
    }

    private void animateStunned() {
        this.animator.setAnim(8);
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.1F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -0.75F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.05F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.05F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.5F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 6.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.rotate(this.Head, 0.25F, 0.5F, 0.5F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, -0.3F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(300);
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, -0.3F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 6.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.rotate(this.Head, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, -0.5F, 0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, -0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, 0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, -0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, 0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, -0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, 0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5F, -0.75F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateCrush() {
        this.animator.setAnim(9);
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.5F, -1.0F, -0.75F);
        this.animator.rotate(this.Frontrightupperarm, 0.5F, 1.0F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.0F, 0.7F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.0F, -0.7F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.6F, -0.8F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.6F, 0.8F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, 0.5F, 0.5F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5F, 0.5F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, 0.5F, -0.5F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5F, -0.5F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.4F);
        this.animator.rotate(this.Abdoman, 0.25F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.05F, -0.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.05F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.05F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.05F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.05F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.05F, -0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.05F, 0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.05F, 0.25F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.25F, 0.0F, -0.4F);
        this.animator.rotate(this.Abdoman, -0.25F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 4.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.3F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 3.5F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, -0.75F, 0.0F, -0.4F);
        this.animator.rotate(this.Abdoman, -0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Thorax, 0.1F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, -1.0F, -6.0F);
        this.animator.rotate(this.Frontleftupperarm, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 0.0F, 0.75F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 0.0F, -0.75F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 0.0F, -0.25F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 0.0F, 0.25F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.4F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.rotate(this.Head, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.Thorax, 0.75F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 6.0F, -12.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.5F, -1.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.5F, 1.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.5F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.5F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.75F, -0.75F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, -0.75F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.5F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.75F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, -0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(70);
        this.animator.rotate(this.Head, 0.0F, 0.0F, -0.75F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, -14.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.3F, -1.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.3F, 1.25F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.3F, 1.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.3F, -1.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.3F, -0.75F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.3F, -0.75F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.3F, 0.5F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.3F, 0.5F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.5F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 14.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.4F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 15.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.rotate(this.Head, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, -0.5F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.25F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, 0.5F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, -0.25F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.6F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Abdoman, 0.0F, 0.0F, -0.5F);
        this.animator.move(this.Thorax, 0.0F, 8.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.6F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.Thorax, 0.0F, 6.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperarm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftupperleg, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg1, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightupperleg2, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerarm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontrightlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Frontleftlowerleg, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backleftlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg1, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Backrightlowerleg2, 0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(60);
    }
}
