//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntityPigZombieTitan;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelPigZombieTitan extends ModelBase {
    public ModelRenderer Torso;
    public ModelRenderer Hat;
    public ModelRenderer LeftThigh;
    public ModelRenderer RightThigh;
    public ModelRenderer MiddleBody;
    public ModelRenderer TopBody;
    public ModelRenderer Head;
    public ModelRenderer Head2;
    public ModelRenderer LeftShoulder;
    public ModelRenderer RightShoulder;
    public ModelRenderer LeftForearm;
    public ModelRenderer RightForearm;
    public ModelRenderer HeldItem;
    public ModelRenderer LeftCalf;
    public ModelRenderer RightCalf;
    private Animator animator;

    public ModelPigZombieTitan() {
        this(0.0F);
    }

    public ModelPigZombieTitan(float p_i1147_1_) {
        this.field_78090_t = 64;
        this.field_78089_u = 64;
        this.Hat = new ModelRenderer(this, 32, 0);
        this.Hat.func_78793_a(0.0F, 0.0F, 0.0F);
        this.Hat.func_78790_a(-4.0F, -8.0F, -4.0F, 8, 8, 8, p_i1147_1_ + 0.5F);
        this.LeftShoulder = new ModelRenderer(this, 40, 16);
        this.LeftShoulder.field_78809_i = true;
        this.LeftShoulder.func_78793_a(6.0F, -2.0F, 0.0F);
        this.LeftShoulder.func_78790_a(-2.0F, -2.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.RightShoulder = new ModelRenderer(this, 40, 16);
        this.RightShoulder.func_78793_a(-6.0F, -2.0F, 0.0F);
        this.RightShoulder.func_78790_a(-2.0F, -2.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.RightForearm = new ModelRenderer(this, 40, 26);
        this.RightForearm.func_78793_a(0.0F, 4.0F, 0.0F);
        this.RightForearm.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.TopBody = new ModelRenderer(this, 16, 16);
        this.TopBody.func_78793_a(0.0F, -4.0F, 0.0F);
        this.TopBody.func_78790_a(-4.0F, -4.0F, -2.0F, 8, 4, 4, p_i1147_1_);
        this.LeftForearm = new ModelRenderer(this, 40, 26);
        this.LeftForearm.field_78809_i = true;
        this.LeftForearm.func_78793_a(0.0F, 4.0F, 0.0F);
        this.LeftForearm.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.MiddleBody = new ModelRenderer(this, 16, 24);
        this.MiddleBody.func_78793_a(0.0F, -4.0F, 0.0F);
        this.MiddleBody.func_78790_a(-4.0F, -4.0F, -2.0F, 8, 4, 4, p_i1147_1_);
        this.RightThigh = new ModelRenderer(this, 0, 16);
        this.RightThigh.func_78793_a(-2.0F, 12.0F, 0.0F);
        this.RightThigh.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.RightCalf = new ModelRenderer(this, 0, 26);
        this.RightCalf.func_78793_a(0.0F, 6.0F, 0.0F);
        this.RightCalf.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.HeldItem = new ModelRenderer(this, 32, 32);
        this.HeldItem.func_78793_a(0.0F, 4.0F, 0.0F);
        this.HeldItem.func_78790_a(0.0F, -12.0F, -12.0F, 0, 16, 16, 0.0F);
        this.Torso = new ModelRenderer(this, 16, 32);
        this.Torso.func_78793_a(0.0F, 12.0F, 0.0F);
        this.Torso.func_78790_a(-4.0F, -4.0F, -2.0F, 8, 4, 4, p_i1147_1_);
        this.LeftThigh = new ModelRenderer(this, 0, 16);
        this.LeftThigh.field_78809_i = true;
        this.LeftThigh.func_78793_a(2.0F, 12.0F, 0.0F);
        this.LeftThigh.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.LeftCalf = new ModelRenderer(this, 0, 26);
        this.LeftCalf.field_78809_i = true;
        this.LeftCalf.func_78793_a(0.0F, 6.0F, 0.0F);
        this.LeftCalf.func_78790_a(-2.0F, 0.0F, -2.0F, 4, 6, 4, p_i1147_1_);
        this.RightThigh.func_78792_a(this.RightCalf);
        this.TopBody.func_78792_a(this.LeftShoulder);
        this.TopBody.func_78792_a(this.RightShoulder);
        this.LeftThigh.func_78792_a(this.LeftCalf);
        this.RightShoulder.func_78792_a(this.RightForearm);
        this.MiddleBody.func_78792_a(this.TopBody);
        this.LeftShoulder.func_78792_a(this.LeftForearm);
        this.Torso.func_78792_a(this.MiddleBody);
        this.RightForearm.func_78792_a(this.HeldItem);
        this.Head = new ModelRenderer(this, 0, 0);
        this.Head.func_78793_a(0.0F, -4.0F, 0.0F);
        this.Head.func_78790_a(-4.0F, -8.0F, -4.0F, 8, 8, 8, p_i1147_1_);
        this.TopBody.func_78792_a(this.Head);
        this.Head.func_78792_a(this.Hat);
        this.Head2 = new ModelRenderer(this, 0, 0);
        this.Head2.func_78790_a(-4.0F, -10.0F, -4.0F, 8, 8, 8, p_i1147_1_ + 2.0F);
        this.Head.func_78792_a(this.Head2);
        this.animator = new Animator(this);
    }

    public void func_78088_a(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntityPigZombieTitan entitytitan = (EntityPigZombieTitan)entity;
        this.animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
        if (entitytitan.func_70631_g_()) {
            this.Head2.field_78807_k = false;
        } else {
            this.Head2.field_78807_k = true;
        }

        if (this.field_78091_s) {
            float f6 = 2.0F;
            GL11.glPushMatrix();
            GL11.glScalef(1.0F / f6, 1.0F / f6, 1.0F / f6);
            GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
            this.RightThigh.func_78785_a(f5);
            this.Torso.func_78785_a(f5);
            this.LeftThigh.func_78785_a(f5);
            GL11.glPopMatrix();
        } else {
            this.RightThigh.func_78785_a(f5);
            this.Torso.func_78785_a(f5);
            this.LeftThigh.func_78785_a(f5);
        }

    }

    public void setAngles() {
        this.LeftShoulder.field_78795_f = (-(float)Math.PI / 2F);
        this.RightShoulder.field_78795_f = (-(float)Math.PI / 2F);
        this.HeldItem.field_78795_f = ((float)Math.PI / 4F);
        this.RightThigh.field_78798_e = 0.0F;
        this.LeftThigh.field_78798_e = 0.0F;
        this.Torso.field_78798_e = 0.0F;
        this.Torso.field_78800_c = 0.0F;
        this.Torso.field_78797_d = 12.0F;
        this.HeldItem.field_78798_e = 0.0F;
        this.HeldItem.field_78800_c = 0.0F;
        this.HeldItem.field_78797_d = 4.0F;
        this.RightThigh.field_78797_d = 12.0F;
        this.LeftThigh.field_78797_d = 12.0F;
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntityPigZombieTitan entitytitan = (EntityPigZombieTitan)entity;
        this.animator.update(entity);
        this.setAngles();
        float fo = 0.22206666F;
        if (entitytitan.deathTicks <= 0) {
            float f6 = MathHelper.func_76134_b(f2 * 0.1F);
            if (entitytitan.getAnimID() == 0) {
                this.MiddleBody.field_78795_f = (0.001F + 0.005F * f6) * (float)Math.PI;
                this.TopBody.field_78795_f = (0.001F + 0.005F * f6) * (float)Math.PI;
                this.Head.field_78795_f = (0.001F + 0.0075F * f6) * (float)Math.PI;
                this.RightShoulder.field_78796_g = (-0.001F + 0.01F * f6) * (float)Math.PI;
                this.LeftShoulder.field_78796_g = (0.001F + -0.01F * f6) * (float)Math.PI;
            }

            if (this.field_78093_q) {
                this.RightThigh.field_78795_f = (-(float)Math.PI / 2F);
                this.LeftThigh.field_78795_f = (-(float)Math.PI / 2F);
                this.RightThigh.field_78796_g = ((float)Math.PI / 10F);
                this.LeftThigh.field_78796_g = (-(float)Math.PI / 10F);
                this.RightCalf.field_78795_f = ((float)Math.PI / 3F);
                this.LeftCalf.field_78795_f = ((float)Math.PI / 3F);
            } else if (entitytitan.getAnimID() == 0) {
                this.Torso.field_78808_h = MathHelper.func_76134_b(f * fo) * 0.1F * f1;
                this.MiddleBody.field_78808_h = MathHelper.func_76134_b(f * fo - 1.0F) * 0.1F * f1;
                this.TopBody.field_78808_h = MathHelper.func_76134_b(f * fo - 2.0F) * 0.1F * f1;
                this.RightThigh.field_78795_f = MathHelper.func_76134_b(f * fo - 0.5F) * 1.25F * f1;
                this.LeftThigh.field_78795_f = MathHelper.func_76134_b(f * fo + 2.6415927F) * 1.25F * f1;
                this.RightCalf.field_78795_f = MathHelper.func_76134_b(f * fo + (float)Math.PI) * 1.25F * f1;
                this.LeftCalf.field_78795_f = MathHelper.func_76134_b(f * fo) * 1.25F * f1;
                this.Torso.field_78797_d = 12.0F - MathHelper.func_76134_b(f * fo * 2.0F + 1.0F) * 2.0F * f1;
                this.RightThigh.field_78797_d = 12.0F - MathHelper.func_76134_b(f * fo * 2.0F + 1.0F) * 2.0F * f1;
                this.LeftThigh.field_78797_d = 12.0F - MathHelper.func_76134_b(f * fo * 2.0F + 1.0F) * 2.0F * f1;
                if (this.RightCalf.field_78795_f < 0.0F) {
                    this.RightCalf.field_78795_f = 0.0F;
                }

                if (this.LeftCalf.field_78795_f < 0.0F) {
                    this.LeftCalf.field_78795_f = 0.0F;
                }
            }

            float faceYaw = f3 * (float)Math.PI / 180.0F;
            float facePitch = f4 * (float)Math.PI / 180.0F;
            if (!entitytitan.field_70122_E && !this.field_78093_q) {
                this.Torso.field_78808_h = 0.0F;
                this.MiddleBody.field_78808_h = 0.0F;
                this.TopBody.field_78808_h = 0.0F;
                this.Head.field_78808_h = 0.0F;
                ModelRenderer var10000 = this.RightShoulder;
                var10000.field_78795_f -= entitytitan.field_70721_aZ;
                var10000 = this.LeftShoulder;
                var10000.field_78795_f -= entitytitan.field_70721_aZ;
                var10000 = this.Head;
                var10000.field_78795_f -= entitytitan.field_70721_aZ;
                var10000 = this.Torso;
                var10000.field_78795_f += entitytitan.field_70721_aZ;
                this.RightThigh.field_78808_h = 0.25F;
                this.LeftThigh.field_78808_h = -0.25F;
                this.RightThigh.field_78796_g = -0.25F;
                this.LeftThigh.field_78796_g = 0.25F;
                this.RightThigh.field_78795_f = MathHelper.func_76134_b(f2 * 0.2F) * 0.25F - (float)(entitytitan.field_70181_x / (double)5.0F) + entitytitan.field_70721_aZ;
                this.LeftThigh.field_78795_f = MathHelper.func_76134_b(f2 * 0.2F - (float)Math.PI) * 0.25F - (float)(entitytitan.field_70181_x / (double)5.0F) + entitytitan.field_70721_aZ;
                this.RightCalf.field_78795_f = 0.5F - MathHelper.func_76134_b(f2 * 0.2F + 0.5F) * 0.5F;
                this.LeftCalf.field_78795_f = 0.5F - MathHelper.func_76134_b(f2 * 0.2F - 2.6415927F) * 0.5F;
            }

            if (entitytitan.animID == 0) {
                ModelRenderer var16 = this.Head;
                var16.field_78795_f += facePitch * 0.3F;
                var16 = this.Head;
                var16.field_78796_g += faceYaw * 0.3F;
                var16 = this.TopBody;
                var16.field_78795_f += facePitch * 0.3F;
                var16 = this.TopBody;
                var16.field_78796_g += faceYaw * 0.3F;
                var16 = this.MiddleBody;
                var16.field_78795_f += facePitch * 0.3F;
                var16 = this.MiddleBody;
                var16.field_78796_g += faceYaw * 0.3F;
            } else {
                ModelRenderer var22 = this.Head;
                var22.field_78795_f += facePitch * 0.9F;
                var22 = this.Head;
                var22.field_78796_g += faceYaw * 0.9F;
            }

            if (entitytitan.getAnimID() == 11 && entitytitan.getAnimTick() > 30 && entitytitan.getAnimTick() < 160) {
                this.Head.field_78808_h = MathHelper.func_76134_b(f2 * 0.25F - 3.0F) * 0.5F;
                this.TopBody.field_78808_h = MathHelper.func_76134_b(f2 * 0.25F - 2.0F) * 0.25F;
                this.MiddleBody.field_78808_h = MathHelper.func_76134_b(f2 * 0.25F - 1.0F) * 0.25F;
                this.Torso.field_78808_h = MathHelper.func_76134_b(f2 * 0.25F) * 0.25F;
            }

            if (entitytitan.getAnimID() == 12 && entitytitan.getAnimTick() > 30 && entitytitan.getAnimTick() < 50) {
                this.RightForearm.field_78795_f = 0.1F * MathHelper.func_76134_b(f2 * 2.0F) * (float)Math.PI;
                this.LeftForearm.field_78795_f = -(0.1F * MathHelper.func_76134_b(f2 * 2.0F) * (float)Math.PI);
            }

            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0:
                        this.animateAntiTitanAttack1();
                        break;
                    case 1:
                        this.animateAntiTitanAttack2();
                        break;
                    case 2:
                        this.animateAntiTitanAttack3();
                        break;
                    case 3:
                        this.animateAntiTitanAttack4();
                }
            }

            this.animateBirth();
            this.animateRoar();
            this.animateRangedAttackThrow();
            this.animateSlam();
            this.animateSwat();
            this.animateSwordDig();
            this.animateLightning();
            this.animateStomp();
            this.animateDownwardSlash();
            this.animateStun();
            this.animateSidewaySlash();
        } else {
            this.animateDeath();
        }

    }

    private void animatePunch() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.2F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.rotate(this.TopBody, 0.0F, 0.0F, -0.5F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 1.5F, 0.0F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 4.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 4.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 4.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.6F, 0.5F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.6F, -0.5F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.2F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.0F, 0.0F, -0.5F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 1.5F, 0.0F, 0.5F);
        this.animator.rotate(this.Torso, 0.9F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.9F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(30);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 5.0F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, -1.5F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Torso, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.RightShoulder, 3.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, -1.0F);
        this.animator.rotate(this.LeftForearm, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, -12.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 1.5F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.5F, 0.0F, -1.2F);
        this.animator.rotate(this.RightForearm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 3.0F, 0.0F, -1.0F);
        this.animator.rotate(this.LeftForearm, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, -11.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(8);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.5F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(12);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.0F);
        this.animator.rotate(this.RightThigh, 1.8F, -10.0F, 0.5F);
        this.animator.rotate(this.RightCalf, 0.0F, 0.0F, 0.5F);
        this.animator.rotate(this.LeftThigh, -0.5F, -10.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 1.75F, -10.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, 0.0F, -12.6F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, -12.6F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, -12.6F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 5.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 1.5F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.Torso, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 2.0F, -1.0F, -1.0F);
        this.animator.rotate(this.LeftForearm, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.0F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, -1.5F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.6F, 0.0F, -1.0F);
        this.animator.rotate(this.LeftShoulder, -0.5F, 0.0F, 1.0F);
        this.animator.rotate(this.RightForearm, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 5.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 5.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.0F, 0.0F, 0.5F);
        this.animator.rotate(this.RightForearm, -1.0F, 0.0F, -0.5F);
        this.animator.rotate(this.HeldItem, -1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 2.0F, -12.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, -12.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, -12.0F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.5F, 0.0F, 0.5F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, -0.5F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateSwat() {
        this.animator.setAnim(2);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.25F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 1.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -1.0F, 0.0F, 1.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -1.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 4.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 4.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 4.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 4.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -1.0F, 0.5F, 0.0F);
        this.animator.rotate(this.LeftThigh, -1.0F, -0.5F, 0.0F);
        this.animator.rotate(this.RightCalf, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -1.0F, 0.0F, -1.0F);
        this.animator.rotate(this.LeftForearm, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.75F, 1.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 4.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSwordDig() {
        this.animator.setAnim(4);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -2.0F, 0.2F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, -0.2F, 0.0F);
        this.animator.rotate(this.RightCalf, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.0F, 0.2F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -0.2F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.0F, -0.4F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.4F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 3.0F, 1.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Head, -1.2F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.4F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.0F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, -1.0F, 0.0F, -0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftForearm, -0.25F, 0.0F, 0.5F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0F, 3.0F, 1.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Head, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.0F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, -1.0F, 0.0F, -0.75F);
        this.animator.rotate(this.RightForearm, 0.0F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.5F);
        this.animator.rotate(this.HeldItem, 2.0F, 0.0F, 2.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSlam() {
        this.animator.setAnim(3);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 0.6F, 0.0F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -1.6F, 0.2F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, 0.2F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.9F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, -0.3F, 0.0F, -0.75F);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0F, 3.0F, 1.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftForearm, -0.5F, 0.0F, 0.5F);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateLightning() {
        this.animator.setAnim(5);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 0.0F, 0.0F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -2.0F, 0.2F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, -0.2F, 0.0F);
        this.animator.rotate(this.RightCalf, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.35F, 0.4F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.35F, -0.4F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, -1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -2.0F, 0.2F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, -0.2F, 0.0F);
        this.animator.rotate(this.RightCalf, 2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.35F, 0.4F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.35F, -0.4F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0F, 3.0F, 1.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.9F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, -0.9F, 0.0F, -0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftForearm, -0.25F, 0.0F, 0.5F);
        this.animator.rotate(this.HeldItem, 2.0F, 0.0F, 2.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(6);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.5F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, -2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -2.0F, 0.2F, 0.75F);
        this.animator.rotate(this.LeftThigh, 0.0F, 0.2F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.5F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.5F);
        this.animator.rotate(this.TopBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, 0.25F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, -0.75F, 0.0F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.5F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.1F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.5F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, -0.4F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.RightForearm, -0.3F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftForearm, -0.3F, 0.0F, -0.75F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, -2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -2.0F, 0.0F, -0.75F);
        this.animator.rotate(this.RightCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.5F, 0.0F, 0.5F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, -0.5F);
        this.animator.rotate(this.TopBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, -0.25F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, -0.75F, 0.0F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.5F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, -0.5F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, -0.5F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, 0.4F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, -0.75F, 0.0F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.3F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftForearm, -0.3F, 0.0F, 0.75F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateDownwardSlash() {
        this.animator.setAnim(7);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, -0.2F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.1F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.1F, 0.0F);
        this.animator.rotate(this.RightShoulder, 1.0F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, 0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 5.5F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, -1.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.Torso, -0.5F, 0.5F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.5F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -1.5F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.75F);
        this.animator.rotate(this.HeldItem, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(50);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 1.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, -0.5F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.5F, -1.5F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 5.5F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 2.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateStun() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.Torso, 0.0F, 1.0F, -3.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -2.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -3.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, -0.5F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.5F, 1.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, -0.5F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -2.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, -0.25F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.55F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(160);
        this.animator.startPhase(40);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, -0.75F, 0.0F, -0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 1.5F, -0.75F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 1.5F, 0.75F, 0.0F);
        this.animator.rotate(this.HeldItem, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 0.0F, 0.0F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.25F, 0.25F);
        this.animator.rotate(this.LeftThigh, -0.25F, -0.25F, -0.25F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.25F, 1.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.25F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.resetPhase(20);
    }

    private void animateSidewaySlash() {
        this.animator.setAnim(9);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.1F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.1F, 0.0F);
        this.animator.rotate(this.RightShoulder, 1.0F, 0.0F, 0.75F);
        this.animator.rotate(this.LeftShoulder, 0.8F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 5.5F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.25F, 0.5F, -0.5F);
        this.animator.rotate(this.MiddleBody, -0.25F, 0.5F, -0.5F);
        this.animator.rotate(this.Torso, -0.25F, 0.5F, -0.5F);
        this.animator.rotate(this.RightShoulder, -1.5F, 0.0F, -1.0F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -1.5F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.75F);
        this.animator.rotate(this.HeldItem, 0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, -0.25F, -0.25F);
        this.animator.rotate(this.MiddleBody, 0.5F, -0.25F, -0.25F);
        this.animator.rotate(this.Torso, 1.0F, -0.25F, -0.5F);
        this.animator.rotate(this.RightShoulder, -1.0F, 0.0F, -1.0F);
        this.animator.rotate(this.LeftShoulder, 1.0F, 0.0F, -0.5F);
        this.animator.rotate(this.RightForearm, 0.5F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 2.0F, 0.0F, -0.5F);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 2.0F, 4.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 4.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 4.0F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.5F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, -0.5F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 2.0F, 8.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 8.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 8.0F);
        this.animator.rotate(this.RightThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.5F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, -0.5F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.5F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 2.0F, 9.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 9.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 9.0F);
        this.animator.rotate(this.RightThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.35F, 0.4F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.35F, -0.4F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 2.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.Torso, 0.0F, 10.0F, 1.0F);
        this.animator.move(this.RightThigh, 0.0F, 10.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 10.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 1.4F, -0.5F, 0.0F);
        this.animator.rotate(this.LeftThigh, 1.4F, 0.5F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.0F, 0.9F, 0.0F);
        this.animator.rotate(this.TopBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 1.75F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.5F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftShoulder, -1.5F, 0.0F, 0.5F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.25F, 0.0F, 0.0F);
        this.animator.move(this.HeldItem, 0.0F, 0.0F, 30.0F);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.move(this.Torso, 0.0F, 10.0F, 1.0F);
        this.animator.move(this.RightThigh, 0.0F, 10.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 10.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 1.6F, -0.5F, 0.0F);
        this.animator.rotate(this.LeftThigh, 1.6F, 0.5F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.0F, 0.9F, 0.0F);
        this.animator.rotate(this.TopBody, -0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.2F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 1.75F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.3F, 0.0F, -0.5F);
        this.animator.rotate(this.LeftShoulder, -1.3F, 0.0F, 0.5F);
        this.animator.rotate(this.RightForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.HeldItem, 0.0F, 0.0F, 30.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateRoar() {
        this.animator.setAnim(11);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.75F);
        this.animator.rotate(this.HeldItem, 0.0F, 0.0F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.25F, 0.25F);
        this.animator.rotate(this.LeftThigh, -0.25F, -0.25F, -0.25F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.25F, 1.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.25F, -1.0F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.25F, 0.25F);
        this.animator.rotate(this.LeftThigh, -0.25F, -0.25F, -0.25F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.25F, 1.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.25F, -1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(140);
        this.animator.resetPhase(40);
    }

    private void animateRangedAttackThrow() {
        this.animator.setAnim(12);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 4.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0F, 2.0F, 5.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 5.5F);
        this.animator.rotate(this.RightThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.65F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, -1.5F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.75F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.75F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.5F, 0.0F, 0.8F);
        this.animator.rotate(this.LeftShoulder, -0.5F, 0.0F, -0.8F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, -0.8F);
        this.animator.rotate(this.LeftForearm, -0.25F, 0.0F, 0.8F);
        this.animator.rotate(this.HeldItem, 4.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 1.0F, -5.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, -5.5F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, -5.5F);
        this.animator.rotate(this.RightThigh, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 4.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.Torso, 0.0F, 11.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 10.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 10.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -1.4F, 1.25F, 0.0F);
        this.animator.rotate(this.LeftThigh, -1.4F, -1.25F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.75F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -0.75F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.25F, -0.5F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 11.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 10.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 10.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -1.4F, 1.25F, 0.0F);
        this.animator.rotate(this.LeftThigh, -1.4F, -1.25F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.75F, 0.75F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -0.75F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.25F, -0.5F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 7.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 7.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -1.0F, -1.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 2.3F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -1.25F, 0.75F, -0.75F);
        this.animator.rotate(this.LeftShoulder, -0.5F, -0.75F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 1.75F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 5.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 5.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 5.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 1.3F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.3F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.6F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, -0.5F, 0.75F, -0.75F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -0.75F, 0.75F);
        this.animator.rotate(this.RightForearm, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 3.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 3.0F, 6.0F);
        this.animator.move(this.RightThigh, 0.0F, 3.0F, 6.0F);
        this.animator.move(this.LeftThigh, 0.0F, 3.0F, 6.0F);
        this.animator.rotate(this.RightThigh, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, 0.5F);
        this.animator.rotate(this.RightShoulder, 0.0F, 0.5F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.0F, -0.5F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 2.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.RightThigh, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, -4.0F);
        this.animator.rotate(this.RightThigh, 0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, -0.5F);
        this.animator.rotate(this.RightShoulder, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 1.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.Torso, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 0.0F, 0.0F);
        this.animator.rotate(this.HeldItem, 0.0F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 1.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 1.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftThigh, -0.25F, 0.0F, 0.0F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.8F, 0.5F, 0.5F);
        this.animator.rotate(this.LeftShoulder, 0.8F, -0.5F, -0.5F);
        this.animator.rotate(this.RightForearm, -1.6F, 0.0F, -0.75F);
        this.animator.rotate(this.LeftForearm, -1.6F, 0.0F, 0.75F);
        this.animator.rotate(this.HeldItem, 0.0F, 0.0F, 0.75F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.25F, 0.25F);
        this.animator.rotate(this.LeftThigh, -0.25F, -0.25F, -0.25F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.25F, 1.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.25F, -1.0F, 0.0F);
        this.animator.rotate(this.RightForearm, 0.0F, -1.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, 0.0F, 1.0F, 0.0F);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.RightThigh, 0.0F, 2.0F, 0.0F);
        this.animator.move(this.LeftThigh, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.RightThigh, -0.25F, 0.25F, 0.25F);
        this.animator.rotate(this.LeftThigh, -0.25F, -0.25F, -0.25F);
        this.animator.rotate(this.RightCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftCalf, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.Head, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.TopBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.MiddleBody, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RightShoulder, 0.5F, 1.0F, 0.0F);
        this.animator.rotate(this.LeftShoulder, 0.5F, -1.0F, 0.0F);
        this.animator.rotate(this.RightForearm, -0.75F, 0.0F, 0.0F);
        this.animator.rotate(this.LeftForearm, -0.75F, 0.0F, 0.0F);
        this.animator.endPhase();
        this.animator.setStationaryPhase(80);
        this.animator.resetPhase(40);
    }
}
